// Shrink every docking target, without shipping a level nobody can finish.
//
// Goal rings and station rings are scaled toward SCALE, then the level is
// re-solved with the real physics. If the smaller ring drops a leg below the
// win floor the ring is grown back one notch at a time until the level passes,
// so a level is never made unwinnable in the name of a visual target.
//
//   node tools/targets.js --level=N [--out=f.json]   # one level
//   node tools/targets.js --apply=DIR                # merge -> levels.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { predict, legStart, legCount, bodiesAt } from '../src/physics.js';
import { LEVELS, SETS } from '../src/levels.js';

const SCALE = 0.5;             // user-chosen: about a moon's width
const LADDER = [0.5, 0.6, 0.72, 0.85, 1];
const MIN_R = 0.7;             // never smaller than the ship's own radius
const MIN_WINS = 3;            // same floor solve.js --fast enforces
const T_SAMPLES = 11;
const HORIZON = 12;

function scaled(level, s) {
  const out = { ...level, goal: { ...level.goal, r: Math.max(+(level.goal.r * s).toFixed(2), MIN_R) } };
  if (level.waypoints) {
    out.waypoints = level.waypoints.map(w => ({ ...w, r: Math.max(+(w.r * s).toFixed(2), MIN_R) }));
  }
  return out;
}

function minWinsOf(level) {
  let worst = Infinity;
  for (let leg = 0; leg < legCount(level); leg++) {
    let wins = 0;
    for (let ti = 0; ti < T_SAMPLES; ti++) {
      const t0 = ti * 0.9;
      const start = legStart(level, leg, bodiesAt(level, t0));
      for (let ang = 0; ang < 360; ang += 3) {
        const rad = (ang * Math.PI) / 180;
        for (let sp = 10; sp <= level.maxLaunch; sp += 4) {
          const r = predict(level, start.x, start.z,
            Math.cos(rad) * sp, Math.sin(rad) * sp, t0, HORIZON, leg);
          if (r.outcome === 'goal' || r.outcome === 'waypoint') wins++;
        }
      }
    }
    worst = Math.min(worst, wins);
    if (worst < MIN_WINS) break;
  }
  return worst;
}

function solveLevel(index) {
  const level = LEVELS[index];
  for (const s of LADDER) {
    const cand = scaled(level, s);
    const wins = minWinsOf(cand);
    if (wins >= MIN_WINS) {
      return {
        index, scale: s, minWins: wins,
        goalR: cand.goal.r,
        waypointR: (cand.waypoints || []).map(w => w.r),
      };
    }
  }
  return { index, scale: 1, minWins: null, goalR: level.goal.r, waypointR: (level.waypoints || []).map(w => w.r) };
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const arg = k => (process.argv.find(a => a.startsWith(`--${k}=`)) || '').split('=')[1];
const applyDir = arg('apply');

if (applyDir) {
  const levels = LEVELS.map(l => ({ ...l, goal: { ...l.goal } }));
  const grown = [];
  for (let i = 0; i < levels.length; i++) {
    const r = JSON.parse(fs.readFileSync(path.join(applyDir, `target-${i}.json`)));
    levels[i].goal.r = r.goalR;
    if (levels[i].waypoints) {
      levels[i].waypoints = levels[i].waypoints.map((w, wi) => ({ ...w, r: r.waypointR[wi] }));
    }
    if (r.scale > SCALE) grown.push(`L${i + 1} @${(r.scale * 100) | 0}%`);
    console.log(`L${String(i + 1).padStart(2)} ${(levels[i].name || '').padEnd(20)} goal ${r.goalR}  (${(r.scale * 100) | 0}% of old)  min-leg ${r.minWins} wins`);
  }
  const setsOut = SETS.map(s => ({ name: s.name, difficulty: s.difficulty }));
  let js = `// GravityLoop — level data (50 levels in 5 themed sets of 10).
// GENERATED by tools/generate.js — edit that file and re-run:
//   node tools/generate.js
// Orbits added by tools/orbits.js; target sizes by tools/targets.js.
// Coordinates: x is right, z is toward the camera (ship starts at +z).
// mass < 0 makes an antimatter star (a hill instead of a well).

export const SETS = ${JSON.stringify(setsOut, null, 2)};

export const LEVELS = ${JSON.stringify(levels, null, 2)};
`;
  js = js.replace(/"color": (\d+)/g, (_, n) => `"color": 0x${Number(n).toString(16)}`);
  fs.writeFileSync(path.join(HERE, '..', 'src', 'levels.js'), js);
  console.log(`\ntargets shrunk to ${SCALE * 100}%` + (grown.length ? `; grown back: ${grown.join(', ')}` : '; none needed growing back'));
} else {
  const idx = Number(arg('level'));
  if (!Number.isInteger(idx)) throw new Error('use --level=N or --apply=DIR');
  const r = solveLevel(idx);
  console.log(`L${idx + 1} ${LEVELS[idx].name || ''}: goal ${r.goalR} (${(r.scale * 100) | 0}%), min-leg ${r.minWins} wins`);
  const out = arg('out');
  if (out) {
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, JSON.stringify(r));
  }
}
