// GravityLoop — level data (50 levels in 5 themed sets of 10).
// GENERATED by tools/generate.js — edit that file and re-run:
//   node tools/generate.js
// Coordinates: x is right, z is toward the camera (ship starts at +z).
// mass < 0 makes a repulsor (a hill instead of a well).

export const SETS = [
  {
    "name": "Cadet Orbits",
    "difficulty": 1
  },
  {
    "name": "Slingshot Academy",
    "difficulty": 2
  },
  {
    "name": "Repulsor Fields",
    "difficulty": 3
  },
  {
    "name": "Clockwork Moons",
    "difficulty": 4
  },
  {
    "name": "Deep Space",
    "difficulty": 5
  }
];

export const LEVELS = [
  {
    "name": "Liftoff",
    "hint": "Drag back from your ship to aim — like a slingshot — then release to launch!",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 42
    },
    "goal": {
      "x": 0,
      "z": -40,
      "r": 7
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Pebble",
        "mass": 260,
        "radius": 3,
        "color": 0x8ecae6,
        "x": -34,
        "z": -4
      }
    ],
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": -16,
      "z": 40
    },
    "goal": {
      "x": -3,
      "z": -41,
      "r": 6.7
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Cinder",
        "mass": 886,
        "radius": 4.5,
        "color": 0x95d5b2,
        "x": 20,
        "z": 20
      }
    ],
    "name": "Two Stones",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": -18,
      "z": 40
    },
    "goal": {
      "x": -1,
      "z": -41,
      "r": 6.4
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Nova",
        "mass": 1069,
        "radius": 4.3,
        "color": 0xbde0fe,
        "x": -27,
        "z": 14
      }
    ],
    "name": "Long Coast",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": -7,
      "z": 40
    },
    "goal": {
      "x": -1,
      "z": -41,
      "r": 6.1
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Lyra",
        "mass": 366,
        "radius": 4.8,
        "color": 0x95d5b2,
        "x": 12,
        "z": -15
      },
      {
        "name": "Pebble",
        "mass": 842,
        "radius": 3.9,
        "color": 0x7ae582,
        "x": 14,
        "z": 9
      }
    ],
    "name": "Soft Curve",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": 11,
      "z": 40
    },
    "goal": {
      "x": -11,
      "z": -41,
      "r": 6.5
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Nova",
        "mass": 998,
        "radius": 4.2,
        "color": 0x7ae582,
        "x": -6,
        "z": -10
      },
      {
        "name": "Frost",
        "mass": 1222,
        "radius": 4,
        "color": 0xff8fa3,
        "x": 21,
        "z": -26
      }
    ],
    "name": "Downhill Run",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": 15,
      "z": 40
    },
    "goal": {
      "x": 2,
      "z": -41,
      "r": 6
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Zephyr",
        "mass": 744,
        "radius": 3.2,
        "color": 0xc8b6ff,
        "x": -8,
        "z": 30
      }
    ],
    "name": "Easy Does It",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": -11,
      "z": 40
    },
    "goal": {
      "x": -16,
      "z": -41,
      "r": 5.8
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Willow",
        "mass": 653,
        "radius": 4.3,
        "color": 0xf4a261,
        "x": -22,
        "z": -10
      }
    ],
    "name": "Twin Dimples",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": -3,
      "z": 40
    },
    "goal": {
      "x": 7,
      "z": -41,
      "r": 5.8
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Nimbus",
        "mass": 820,
        "radius": 5,
        "color": 0xffc8dd,
        "x": -38,
        "z": 13
      }
    ],
    "name": "Drift Lane",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "name": "The Dip",
    "hint": "That well will bend your shot. Watch the prediction line and aim off-center.",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 42
    },
    "goal": {
      "x": 0,
      "z": -42,
      "r": 5.5
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mint",
        "mass": 1300,
        "radius": 5,
        "color": 0x7ae582,
        "x": 15,
        "z": 0
      }
    ],
    "difficulty": 1
  },
  {
    "extent": 56,
    "ship": {
      "x": 17,
      "z": 40
    },
    "goal": {
      "x": -18,
      "z": -41,
      "r": 6.1
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Opal",
        "mass": 968,
        "radius": 4.7,
        "color": 0xbde0fe,
        "x": 6,
        "z": -3
      },
      {
        "name": "Rhea",
        "mass": 607,
        "radius": 3.4,
        "color": 0xf4a261,
        "x": 28,
        "z": 16
      }
    ],
    "name": "Graduation",
    "hint": "Small wells, gentle bends. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": -19,
      "z": 43
    },
    "goal": {
      "x": -26,
      "z": -44,
      "r": 5.5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mica",
        "mass": 2076,
        "radius": 6.8,
        "color": 0x95d5b2,
        "x": -18,
        "z": -2
      },
      {
        "name": "Juno",
        "mass": 1361,
        "radius": 4.1,
        "color": 0x7ae582,
        "x": 31,
        "z": -23
      },
      {
        "name": "Echo",
        "mass": 1177,
        "radius": 5.4,
        "color": 0xffc8dd,
        "x": 12,
        "z": 18
      }
    ],
    "name": "Around the Bend",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 20,
      "z": 43
    },
    "goal": {
      "x": -6,
      "z": -44,
      "r": 5.4
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Pebble",
        "mass": 1961,
        "radius": 7,
        "color": 0xf4a261,
        "x": 1,
        "z": 11
      },
      {
        "name": "Willow",
        "mass": 1167,
        "radius": 4,
        "color": 0xbde0fe,
        "x": -38,
        "z": 23
      }
    ],
    "name": "Deep Dive",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 15,
      "z": 43
    },
    "goal": {
      "x": 11,
      "z": -44,
      "r": 5.4
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Pip",
        "mass": 1769,
        "radius": 7,
        "color": 0xc8b6ff,
        "x": 20,
        "z": -3
      },
      {
        "name": "Iris",
        "mass": 819,
        "radius": 4.2,
        "color": 0x90e0ef,
        "x": -19,
        "z": -12
      }
    ],
    "name": "Hairpin",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 10,
      "z": 43
    },
    "goal": {
      "x": -13,
      "z": -44,
      "r": 5.5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mica",
        "mass": 1869,
        "radius": 6.1,
        "color": 0x95d5b2,
        "x": -9,
        "z": 7
      },
      {
        "name": "Koa",
        "mass": 1475,
        "radius": 4.8,
        "color": 0x90e0ef,
        "x": 32,
        "z": -28
      }
    ],
    "name": "Double Trouble",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "name": "Slingshot",
    "hint": "No way through — so curve around. Dive into the well and let it fling you!",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Rusty",
        "mass": 2100,
        "radius": 7,
        "color": 0xff8fa3,
        "x": 0,
        "z": -2
      }
    ],
    "difficulty": 2
  },
  {
    "name": "The Saddle",
    "hint": "Two wells, one ridge between them. Thread the saddle — or swing wide.",
    "extent": 62,
    "ship": {
      "x": -10,
      "z": 44
    },
    "goal": {
      "x": 4,
      "z": -44,
      "r": 4.5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Castor",
        "mass": 1500,
        "radius": 6,
        "color": 0xffd166,
        "x": -16,
        "z": 0
      },
      {
        "name": "Pollux",
        "mass": 1500,
        "radius": 6,
        "color": 0xf4a261,
        "x": 16,
        "z": 0
      }
    ],
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": -9,
      "z": 43
    },
    "goal": {
      "x": -20,
      "z": -44,
      "r": 5.4
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mint",
        "mass": 1703,
        "radius": 6.9,
        "color": 0xc8b6ff,
        "x": -20,
        "z": 5
      },
      {
        "name": "Quartz",
        "mass": 1269,
        "radius": 5.3,
        "color": 0x95d5b2,
        "x": -41,
        "z": 13
      }
    ],
    "name": "Corner Pocket",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 9,
      "z": 43
    },
    "goal": {
      "x": 14,
      "z": -44,
      "r": 5.4
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mica",
        "mass": 1733,
        "radius": 6.7,
        "color": 0xbde0fe,
        "x": 17,
        "z": -4
      },
      {
        "name": "Iris",
        "mass": 1383,
        "radius": 4.1,
        "color": 0xbde0fe,
        "x": 10,
        "z": -23
      }
    ],
    "name": "Gravity Assist",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 17,
      "z": 43
    },
    "goal": {
      "x": 20,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Lyra",
        "mass": 2015,
        "radius": 6.8,
        "color": 0x7ae582,
        "x": 14,
        "z": 8
      },
      {
        "name": "Echo",
        "mass": 1115,
        "radius": 5,
        "color": 0x7ae582,
        "x": 34,
        "z": 13
      },
      {
        "name": "Vesta",
        "mass": 859,
        "radius": 4.9,
        "color": 0xf4a261,
        "x": -18,
        "z": 35
      }
    ],
    "name": "Full Send",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 20,
      "z": 43
    },
    "goal": {
      "x": 29,
      "z": -44,
      "r": 5.4
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Opal",
        "mass": 2037,
        "radius": 6.2,
        "color": 0x90e0ef,
        "x": 31,
        "z": 9
      },
      {
        "name": "Sage",
        "mass": 1071,
        "radius": 5.2,
        "color": 0xbde0fe,
        "x": 21,
        "z": -10
      }
    ],
    "name": "Masterclass",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": -23,
      "z": 45
    },
    "goal": {
      "x": -6,
      "z": -45,
      "r": 5.2
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Nope",
        "mass": -1445,
        "radius": 4.6,
        "color": 0xff6b35,
        "x": 6,
        "z": -21
      },
      {
        "name": "Mica",
        "mass": 942,
        "radius": 4.6,
        "color": 0x90e0ef,
        "x": 46,
        "z": -23
      },
      {
        "name": "Vesta",
        "mass": 1224,
        "radius": 4.6,
        "color": 0x90e0ef,
        "x": -28,
        "z": -11
      }
    ],
    "name": "Uphill Battle",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": -22,
      "z": 45
    },
    "goal": {
      "x": -6,
      "z": -45,
      "r": 4.9
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Grudge",
        "mass": -1438,
        "radius": 4.5,
        "color": 0xff6b35,
        "x": 8,
        "z": 5
      },
      {
        "name": "Echo",
        "mass": 1141,
        "radius": 4.4,
        "color": 0x7ae582,
        "x": -24,
        "z": -10
      }
    ],
    "name": "The Pass",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 21,
      "z": 45
    },
    "goal": {
      "x": -15,
      "z": -45,
      "r": 5.1
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Grudge",
        "mass": -1282,
        "radius": 4.3,
        "color": 0xff6b35,
        "x": 15,
        "z": -14
      },
      {
        "name": "Fern",
        "mass": 1060,
        "radius": 4.4,
        "color": 0xffd166,
        "x": -27,
        "z": -30
      },
      {
        "name": "Nimbus",
        "mass": 1357,
        "radius": 5.2,
        "color": 0xf4a261,
        "x": 46,
        "z": 6
      }
    ],
    "name": "Push and Pull",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 5,
      "z": 45
    },
    "goal": {
      "x": 14,
      "z": -45,
      "r": 4.7
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Pusher",
        "mass": -1766,
        "radius": 4.6,
        "color": 0xff6b35,
        "x": 26,
        "z": 3
      },
      {
        "name": "Shove",
        "mass": -926,
        "radius": 4.1,
        "color": 0xff6b35,
        "x": -9,
        "z": 19
      },
      {
        "name": "Onyx",
        "mass": 1569,
        "radius": 5.2,
        "color": 0xf4a261,
        "x": -10,
        "z": -27
      },
      {
        "name": "Sage",
        "mass": 1485,
        "radius": 4.7,
        "color": 0x7ae582,
        "x": -26,
        "z": 15
      }
    ],
    "name": "Ridge Runner",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 18,
      "z": 45
    },
    "goal": {
      "x": -29,
      "z": -45,
      "r": 5.3
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Nope",
        "mass": -1047,
        "radius": 4.8,
        "color": 0xff6b35,
        "x": -23,
        "z": -2
      },
      {
        "name": "Rhea",
        "mass": 1097,
        "radius": 5.4,
        "color": 0x90e0ef,
        "x": 20,
        "z": -28
      }
    ],
    "name": "Between Hills",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": -24,
      "z": 45
    },
    "goal": {
      "x": 0,
      "z": -45,
      "r": 4.8
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Grudge",
        "mass": -1704,
        "radius": 4.1,
        "color": 0xff6b35,
        "x": -31,
        "z": 8
      },
      {
        "name": "Bristle",
        "mass": -1681,
        "radius": 4.2,
        "color": 0xff6b35,
        "x": -34,
        "z": -12
      },
      {
        "name": "Onyx",
        "mass": 1174,
        "radius": 4.4,
        "color": 0xffd166,
        "x": 29,
        "z": 6
      }
    ],
    "name": "Backpressure",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "name": "Repulsor Ridge",
    "hint": "That hill pushes you AWAY. Ride the pass between the hill and the well.",
    "extent": 62,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Nope",
        "mass": -1200,
        "radius": 4.5,
        "color": 0xff6b35,
        "x": -12,
        "z": 0
      },
      {
        "name": "Anchor",
        "mass": 1300,
        "radius": 5,
        "color": 0x90e0ef,
        "x": 16,
        "z": -2
      }
    ],
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": -4,
      "z": 45
    },
    "goal": {
      "x": -1,
      "z": -45,
      "r": 5.3
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Shove",
        "mass": -1166,
        "radius": 4.6,
        "color": 0xff6b35,
        "x": -13,
        "z": -10
      },
      {
        "name": "Basil",
        "mass": 1145,
        "radius": 5.3,
        "color": 0x95d5b2,
        "x": -17,
        "z": 10
      },
      {
        "name": "Halo",
        "mass": 919,
        "radius": 5.1,
        "color": 0x95d5b2,
        "x": 27,
        "z": -13
      }
    ],
    "name": "The Squeeze",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 7,
      "z": 45
    },
    "goal": {
      "x": 20,
      "z": -45,
      "r": 4.9
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Bristle",
        "mass": -1483,
        "radius": 4.8,
        "color": 0xff6b35,
        "x": 2,
        "z": -3
      },
      {
        "name": "Cinder",
        "mass": 1159,
        "radius": 4.8,
        "color": 0xff8fa3,
        "x": -34,
        "z": 11
      }
    ],
    "name": "Turbulence",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 22,
      "z": 45
    },
    "goal": {
      "x": -17,
      "z": -45,
      "r": 5.2
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Static",
        "mass": -1217,
        "radius": 4.8,
        "color": 0xff6b35,
        "x": -15,
        "z": -10
      },
      {
        "name": "Pusher",
        "mass": -1568,
        "radius": 4.8,
        "color": 0xff6b35,
        "x": 18,
        "z": 16
      },
      {
        "name": "Mica",
        "mass": 1511,
        "radius": 5.2,
        "color": 0xff8fa3,
        "x": 4,
        "z": -33
      },
      {
        "name": "Quartz",
        "mass": 1517,
        "radius": 5,
        "color": 0x8ecae6,
        "x": 29,
        "z": -17
      }
    ],
    "name": "Summit",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": -29,
      "z": 46
    },
    "goal": {
      "x": 7,
      "z": -47,
      "r": 5.2
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Lyra",
        "mass": 2365,
        "radius": 6.6,
        "color": 0x95d5b2,
        "x": -7,
        "z": -1
      },
      {
        "name": "Jasper",
        "mass": 532,
        "radius": 3.4,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 20,
          "omega": 0.47,
          "phase": 0.17
        }
      },
      {
        "name": "Atlas",
        "mass": 679,
        "radius": 4,
        "color": 0xbde0fe,
        "x": 34,
        "z": 26
      }
    ],
    "name": "Tick Tock",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -21,
      "z": 46
    },
    "goal": {
      "x": -30,
      "z": -47,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Echo",
        "mass": 1373,
        "radius": 4.8,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -10,
          "cz": -13,
          "radius": 14,
          "omega": -0.46,
          "phase": 1.11
        }
      },
      {
        "name": "Juno",
        "mass": 1173,
        "radius": 5.2,
        "color": 0x8ecae6,
        "orbit": {
          "cx": -10,
          "cz": -13,
          "radius": 14,
          "omega": -0.46,
          "phase": 4.25
        }
      }
    ],
    "name": "Orbit Window",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -9,
      "z": 46
    },
    "goal": {
      "x": 30,
      "z": -47,
      "r": 5.2
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Dune",
        "mass": 1142,
        "radius": 5.1,
        "color": 0xbde0fe,
        "orbit": {
          "cx": -6,
          "cz": -5,
          "radius": 12.8,
          "omega": 0.39,
          "phase": 2.26
        }
      },
      {
        "name": "Basil",
        "mass": 1285,
        "radius": 4.9,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -6,
          "cz": -5,
          "radius": 12.8,
          "omega": 0.39,
          "phase": 5.4
        }
      }
    ],
    "name": "Waltz",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -19,
      "z": 46
    },
    "goal": {
      "x": 20,
      "z": -47,
      "r": 5.1
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Lumen",
        "mass": 2152,
        "radius": 6.8,
        "color": 0x7ae582,
        "x": 6,
        "z": -6
      },
      {
        "name": "Cinder",
        "mass": 577,
        "radius": 3,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 19.3,
          "omega": 0.73,
          "phase": 5.43
        }
      },
      {
        "name": "Quartz",
        "mass": 876,
        "radius": 4.9,
        "color": 0xff8fa3,
        "x": 11,
        "z": 33
      }
    ],
    "name": "Phase Shift",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "name": "Moonshot",
    "hint": "The moon keeps moving — even while you aim. Time your release!",
    "extent": 62,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -46,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Aegis",
        "mass": 2200,
        "radius": 7,
        "color": 0xbde0fe,
        "x": 0,
        "z": -4
      },
      {
        "name": "Luna",
        "mass": 520,
        "radius": 3,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 20,
          "omega": 0.7,
          "phase": 0.8
        }
      }
    ],
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -22,
      "z": 46
    },
    "goal": {
      "x": 0,
      "z": -47,
      "r": 4.9
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Halo",
        "mass": 2050,
        "radius": 6.8,
        "color": 0x7ae582,
        "x": -10,
        "z": -1
      },
      {
        "name": "Lumen",
        "mass": 609,
        "radius": 3.4,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 21.7,
          "omega": -0.55,
          "phase": 2.34
        }
      }
    ],
    "name": "Metronome",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": 12,
      "z": 46
    },
    "goal": {
      "x": -31,
      "z": -47,
      "r": 4.8
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Halo",
        "mass": 1315,
        "radius": 5.4,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -11,
          "cz": 5,
          "radius": 14.2,
          "omega": 0.37,
          "phase": 4.09
        }
      },
      {
        "name": "Nimbus",
        "mass": 1299,
        "radius": 4.8,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -11,
          "cz": 5,
          "radius": 14.2,
          "omega": 0.37,
          "phase": 7.23
        }
      }
    ],
    "name": "Eclipse",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": 5,
      "z": 46
    },
    "goal": {
      "x": -9,
      "z": -47,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Pebble",
        "mass": 1884,
        "radius": 7,
        "color": 0xffd166,
        "x": -11,
        "z": -8
      },
      {
        "name": "Nimbus",
        "mass": 411,
        "radius": 3.2,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 19.6,
          "omega": 0.71,
          "phase": 5.63
        }
      }
    ],
    "name": "Revolution",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": 21,
      "z": 46
    },
    "goal": {
      "x": -16,
      "z": -47,
      "r": 4.9
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Opal",
        "mass": 1308,
        "radius": 5.4,
        "color": 0x8ecae6,
        "orbit": {
          "cx": 9,
          "cz": -10,
          "radius": 14.1,
          "omega": -0.33,
          "phase": 4.62
        }
      },
      {
        "name": "Juno",
        "mass": 1339,
        "radius": 4.6,
        "color": 0xffd166,
        "orbit": {
          "cx": 9,
          "cz": -10,
          "radius": 14.1,
          "omega": -0.33,
          "phase": 7.76
        }
      },
      {
        "name": "Lyra",
        "mass": 801,
        "radius": 4.7,
        "color": 0x8ecae6,
        "x": -39,
        "z": 33
      }
    ],
    "name": "Perfect Timing",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -25,
      "z": 46
    },
    "goal": {
      "x": 26,
      "z": -47,
      "r": 4.8
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Atlas",
        "mass": 1353,
        "radius": 5.5,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -9,
          "cz": 9,
          "radius": 14.1,
          "omega": 0.45,
          "phase": 4.34
        }
      },
      {
        "name": "Dune",
        "mass": 1236,
        "radius": 5.4,
        "color": 0xffd166,
        "orbit": {
          "cx": -9,
          "cz": 9,
          "radius": 14.1,
          "omega": 0.45,
          "phase": 7.48
        }
      },
      {
        "name": "Quartz",
        "mass": 842,
        "radius": 4.4,
        "color": 0x95d5b2,
        "x": -44,
        "z": -13
      }
    ],
    "name": "Clockwork",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "name": "Event Horizon",
    "hint": "Nothing escapes the red ring. Skim close for a huge slingshot — but not TOO close.",
    "extent": 64,
    "ship": {
      "x": -38,
      "z": 44
    },
    "goal": {
      "x": 34,
      "z": -44,
      "r": 4.5
    },
    "maxLaunch": 44,
    "fuel": 4,
    "bodies": [
      {
        "name": "Maw",
        "mass": 5200,
        "radius": 3.5,
        "horizon": 6.5,
        "color": 0x1a1a2e,
        "x": 0,
        "z": 0,
        "type": "blackhole"
      }
    ],
    "difficulty": 5
  },
  {
    "extent": 74,
    "ship": {
      "x": 12,
      "z": 53
    },
    "goal": {
      "x": -35,
      "z": -54,
      "r": 4.6
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Helios",
        "mass": 3364,
        "radius": 9,
        "color": 0xffd166,
        "x": 3,
        "z": -4
      },
      {
        "name": "Jasper",
        "mass": 607,
        "radius": 3.6,
        "color": 0xffd166,
        "orbit": {
          "cx": 3,
          "cz": -4,
          "radius": 21,
          "omega": 0.22,
          "phase": 6.26
        }
      },
      {
        "name": "Mint",
        "mass": 810,
        "radius": 3.8,
        "color": 0x7ae582,
        "orbit": {
          "cx": 3,
          "cz": -4,
          "radius": 38,
          "omega": 0.37,
          "phase": 3.05
        }
      }
    ],
    "name": "Three-Body Problem",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "extent": 71,
    "ship": {
      "x": 25,
      "z": 51
    },
    "goal": {
      "x": -20,
      "z": -52,
      "r": 4.7
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2662,
        "radius": 9.2,
        "color": 0xffd166,
        "x": 7,
        "z": -3
      },
      {
        "name": "Coral",
        "mass": 941,
        "radius": 3.6,
        "color": 0xf4a261,
        "orbit": {
          "cx": 7,
          "cz": -3,
          "radius": 21,
          "omega": -0.42,
          "phase": 1.72
        }
      },
      {
        "name": "Juno",
        "mass": 908,
        "radius": 4.1,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 7,
          "cz": -3,
          "radius": 38,
          "omega": 0.32,
          "phase": 5.03
        }
      }
    ],
    "name": "Star System",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "extent": 68,
    "ship": {
      "x": -22,
      "z": 49
    },
    "goal": {
      "x": 6,
      "z": -50,
      "r": 4.5
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 2823,
        "radius": 8.4,
        "color": 0xffd166,
        "x": 0,
        "z": 1
      },
      {
        "name": "Pebble",
        "mass": 800,
        "radius": 4.4,
        "color": 0xff8fa3,
        "orbit": {
          "cx": 0,
          "cz": 1,
          "radius": 21,
          "omega": -0.28,
          "phase": 5.66
        }
      },
      {
        "name": "Juno",
        "mass": 739,
        "radius": 3.9,
        "color": 0xf4a261,
        "orbit": {
          "cx": 0,
          "cz": 1,
          "radius": 38,
          "omega": 0.16,
          "phase": 0.64
        }
      }
    ],
    "name": "Dark Passage",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "extent": 67,
    "ship": {
      "x": -27,
      "z": 48
    },
    "goal": {
      "x": 25,
      "z": -49,
      "r": 4.6
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Vera",
        "mass": 3213,
        "radius": 8.4,
        "color": 0xff9e6b,
        "x": 6,
        "z": 4
      },
      {
        "name": "Lyra",
        "mass": 614,
        "radius": 4.1,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 6,
          "cz": 4,
          "radius": 21,
          "omega": -0.26,
          "phase": 4.41
        }
      },
      {
        "name": "Jasper",
        "mass": 528,
        "radius": 3.7,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 6,
          "cz": 4,
          "radius": 38,
          "omega": -0.33,
          "phase": 5.1
        }
      }
    ],
    "name": "Planetfall",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "extent": 68,
    "ship": {
      "x": -30,
      "z": 49
    },
    "goal": {
      "x": 14,
      "z": -50,
      "r": 4.8
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 3374,
        "radius": 8.3,
        "color": 0xffd166,
        "x": 3,
        "z": 1
      },
      {
        "name": "Cinder",
        "mass": 781,
        "radius": 4.6,
        "color": 0x90e0ef,
        "orbit": {
          "cx": 3,
          "cz": 1,
          "radius": 21,
          "omega": -0.34,
          "phase": 5.17
        }
      },
      {
        "name": "Rhea",
        "mass": 791,
        "radius": 3.8,
        "color": 0xff8fa3,
        "orbit": {
          "cx": 3,
          "cz": 1,
          "radius": 38,
          "omega": 0.22,
          "phase": 6.14
        }
      }
    ],
    "name": "The Gauntlet",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "extent": 70,
    "ship": {
      "x": -16,
      "z": 50
    },
    "goal": {
      "x": 20,
      "z": -51,
      "r": 4.7
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Vera",
        "mass": 3068,
        "radius": 9.4,
        "color": 0xffb703,
        "x": 6,
        "z": 2
      },
      {
        "name": "Zephyr",
        "mass": 905,
        "radius": 3.7,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 6,
          "cz": 2,
          "radius": 21,
          "omega": 0.37,
          "phase": 6.21
        }
      },
      {
        "name": "Nimbus",
        "mass": 988,
        "radius": 4.8,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 6,
          "cz": 2,
          "radius": 38,
          "omega": 0.38,
          "phase": 2.11
        }
      }
    ],
    "name": "Singularity",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "extent": 70,
    "ship": {
      "x": 21,
      "z": 50
    },
    "goal": {
      "x": 12,
      "z": -51,
      "r": 4.8
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Helios",
        "mass": 3601,
        "radius": 8.7,
        "color": 0xffd166,
        "x": 0,
        "z": 1
      },
      {
        "name": "Willow",
        "mass": 976,
        "radius": 4.5,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 0,
          "cz": 1,
          "radius": 21,
          "omega": 0.35,
          "phase": 4.21
        }
      },
      {
        "name": "Dune",
        "mass": 1046,
        "radius": 4.3,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 0,
          "cz": 1,
          "radius": 38,
          "omega": 0.44,
          "phase": 3.37
        }
      }
    ],
    "name": "Far Shore",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "extent": 70,
    "ship": {
      "x": 15,
      "z": 50
    },
    "goal": {
      "x": -24,
      "z": -51,
      "r": 4.6
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 3401,
        "radius": 9.5,
        "color": 0xff9e6b,
        "x": -3,
        "z": -3
      },
      {
        "name": "Quartz",
        "mass": 508,
        "radius": 4.1,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -3,
          "cz": -3,
          "radius": 21,
          "omega": -0.43,
          "phase": 2.34
        }
      },
      {
        "name": "Nimbus",
        "mass": 859,
        "radius": 4.7,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -3,
          "cz": -3,
          "radius": 38,
          "omega": 0.35,
          "phase": 4.8
        }
      }
    ],
    "name": "Last Light",
    "hint": "Whole solar systems between you and the goal. Chart your course.",
    "difficulty": 5
  },
  {
    "name": "Grand Tour",
    "hint": "Everything at once. Take your time — plot the long way round.",
    "extent": 74,
    "ship": {
      "x": 30,
      "z": 56
    },
    "goal": {
      "x": -34,
      "z": -50,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Titan",
        "mass": 1700,
        "radius": 6,
        "color": 0xffd166,
        "x": 26,
        "z": 14
      },
      {
        "name": "Wisp",
        "mass": 420,
        "radius": 2.5,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 15,
          "omega": 0.8,
          "phase": 2.1
        }
      },
      {
        "name": "Nope II",
        "mass": -1600,
        "radius": 4.5,
        "color": 0xff6b35,
        "x": 2,
        "z": -4
      },
      {
        "name": "Maw II",
        "mass": 4200,
        "radius": 3,
        "horizon": 5.5,
        "color": 0x1a1a2e,
        "x": -26,
        "z": -18,
        "type": "blackhole"
      }
    ],
    "difficulty": 5
  }
];
