// GravityLoop — level data (50 levels in 5 themed sets of 10).
// GENERATED by tools/generate.js — edit that file and re-run:
//   node tools/generate.js
// Coordinates: x is right, z is toward the camera (ship starts at +z).
// mass < 0 makes a repulsor (a hill instead of a well).

export const SETS = [
  {
    "name": "Cadet Orbits",
    "difficulty": 1
  },
  {
    "name": "Slingshot Academy",
    "difficulty": 2
  },
  {
    "name": "Repulsor Fields",
    "difficulty": 3
  },
  {
    "name": "Clockwork Moons",
    "difficulty": 4
  },
  {
    "name": "Deep Space",
    "difficulty": 5
  }
];

export const LEVELS = [
  {
    "name": "Liftoff",
    "hint": "Drag back from your ship to aim — like a slingshot — then release to launch!",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 42
    },
    "goal": {
      "x": 0,
      "z": -40,
      "r": 7
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Pebble",
        "mass": 260,
        "radius": 3,
        "color": 0x8ecae6,
        "x": -34,
        "z": -4
      }
    ],
    "difficulty": 1
  },
  {
    "name": "The Dip",
    "hint": "That well will bend your shot. Watch the prediction line and aim off-center.",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 42
    },
    "goal": {
      "x": 0,
      "z": -42,
      "r": 5.5
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mint",
        "mass": 1300,
        "radius": 5,
        "color": 0x7ae582,
        "x": 15,
        "z": 0
      }
    ],
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": -1,
      "z": 42
    },
    "goal": {
      "x": -2,
      "z": -42,
      "r": 6
    },
    "maxLaunch": 51,
    "fuel": 3,
    "bodies": [
      {
        "name": "Echo",
        "mass": 1322,
        "radius": 4.6,
        "color": 0x90e0ef,
        "x": 19,
        "z": 24
      },
      {
        "name": "Sage",
        "mass": 616,
        "radius": 4.8,
        "color": 0x7ae582,
        "x": -40,
        "z": 22
      }
    ],
    "pickups": [
      {
        "x": -5,
        "z": -14,
        "fuel": 1.5
      }
    ],
    "name": "Fuel Run",
    "hint": "Orange fuel cells sit near good routes — big launches burn fuel, so top up!",
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": 14,
      "z": 42
    },
    "goal": {
      "x": 7,
      "z": -42,
      "r": 5.9
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Lyra",
        "mass": 1186,
        "radius": 4.6,
        "color": 0x90e0ef,
        "x": -19,
        "z": -16
      },
      {
        "name": "Dune",
        "mass": 572,
        "radius": 4.6,
        "color": 0xf4a261,
        "x": 24,
        "z": -27
      }
    ],
    "pickups": [
      {
        "x": 10,
        "z": -5,
        "fuel": 1.5
      }
    ],
    "name": "Long Coast",
    "hint": "Multiple wells bend every shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": -15,
      "z": 42
    },
    "goal": {
      "x": -20,
      "z": -42,
      "r": 5.8
    },
    "maxLaunch": 51,
    "fuel": 3,
    "bodies": [
      {
        "name": "Willow",
        "mass": 1198,
        "radius": 3.1,
        "color": 0xf4a261,
        "x": 41,
        "z": 8
      },
      {
        "name": "Echo",
        "mass": 1082,
        "radius": 3.4,
        "color": 0xffd166,
        "x": 15,
        "z": 7
      }
    ],
    "pickups": [
      {
        "x": -23,
        "z": -16,
        "fuel": 1.5
      }
    ],
    "name": "Downhill Run",
    "hint": "Multiple wells bend every shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": 9,
      "z": 42
    },
    "goal": {
      "x": 12,
      "z": -42,
      "r": 5.6
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Fern",
        "mass": 1040,
        "radius": 4.3,
        "color": 0xffc8dd,
        "x": 35,
        "z": -4
      },
      {
        "name": "Cinder",
        "mass": 1132,
        "radius": 3.3,
        "color": 0x7ae582,
        "x": -31,
        "z": 29
      },
      {
        "name": "Koa",
        "mass": 409,
        "radius": 3.6,
        "color": 0x90e0ef,
        "x": -4,
        "z": -31
      }
    ],
    "pickups": [
      {
        "x": 9,
        "z": 13,
        "fuel": 1.5
      }
    ],
    "name": "Easy Does It",
    "hint": "Multiple wells bend every shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": -7,
      "z": 42
    },
    "goal": {
      "x": 17,
      "z": -42,
      "r": 5.5
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Dune",
        "mass": 716,
        "radius": 4.4,
        "color": 0xff8fa3,
        "x": 40,
        "z": 26
      },
      {
        "name": "Coral",
        "mass": 470,
        "radius": 4.2,
        "color": 0xff8fa3,
        "x": 43,
        "z": 11
      }
    ],
    "pickups": [
      {
        "x": -1,
        "z": 11,
        "fuel": 1.5
      }
    ],
    "name": "Twin Dimples",
    "hint": "Multiple wells bend every shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": -12,
      "z": 42
    },
    "goal": {
      "x": -17,
      "z": -42,
      "r": 5.4
    },
    "maxLaunch": 51,
    "fuel": 3,
    "bodies": [
      {
        "name": "Dune",
        "mass": 1156,
        "radius": 3.6,
        "color": 0x8ecae6,
        "x": -37,
        "z": -14
      },
      {
        "name": "Halo",
        "mass": 706,
        "radius": 3.6,
        "color": 0xff8fa3,
        "x": 1,
        "z": 12
      },
      {
        "name": "Lumen",
        "mass": 545,
        "radius": 3.7,
        "color": 0xf4a261,
        "x": 15,
        "z": 32
      }
    ],
    "pickups": [
      {
        "x": -14,
        "z": 5,
        "fuel": 1.5
      }
    ],
    "name": "Drift Lane",
    "hint": "Multiple wells bend every shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": -23,
      "z": 42
    },
    "goal": {
      "x": -13,
      "z": -42,
      "r": 5.3
    },
    "maxLaunch": 52,
    "fuel": 3,
    "bodies": [
      {
        "name": "Vesta",
        "mass": 1065,
        "radius": 3.8,
        "color": 0xffc8dd,
        "x": 28,
        "z": 1
      },
      {
        "name": "Coral",
        "mass": 717,
        "radius": 4.5,
        "color": 0xf4a261,
        "x": 1,
        "z": -7
      },
      {
        "name": "Nimbus",
        "mass": 876,
        "radius": 3.4,
        "color": 0x7ae582,
        "x": 15,
        "z": 7
      }
    ],
    "pickups": [
      {
        "x": -16,
        "z": -4,
        "fuel": 1.5
      }
    ],
    "name": "Warm Up",
    "hint": "Multiple wells bend every shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 58,
    "ship": {
      "x": 10,
      "z": 42
    },
    "goal": {
      "x": -15,
      "z": -42,
      "r": 5.1
    },
    "maxLaunch": 51,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mica",
        "mass": 679,
        "radius": 4.9,
        "color": 0xffc8dd,
        "x": -36,
        "z": 17
      },
      {
        "name": "Vesta",
        "mass": 1135,
        "radius": 3.9,
        "color": 0x8ecae6,
        "x": 25,
        "z": -31
      },
      {
        "name": "Jasper",
        "mass": 1063,
        "radius": 3.3,
        "color": 0x95d5b2,
        "x": -6,
        "z": -4
      }
    ],
    "pickups": [
      {
        "x": 3,
        "z": -10,
        "fuel": 1.5
      }
    ],
    "name": "Graduation",
    "hint": "Multiple wells bend every shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "name": "Slingshot",
    "hint": "No way through — so curve around. Dive into the well and let it fling you!",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Rusty",
        "mass": 2100,
        "radius": 7,
        "color": 0xff8fa3,
        "x": 0,
        "z": -2
      }
    ],
    "difficulty": 2
  },
  {
    "name": "The Saddle",
    "hint": "Two wells, one ridge between them. Thread the saddle — or swing wide.",
    "extent": 62,
    "ship": {
      "x": -10,
      "z": 44
    },
    "goal": {
      "x": 4,
      "z": -44,
      "r": 4.5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Castor",
        "mass": 1500,
        "radius": 6,
        "color": 0xffd166,
        "x": -16,
        "z": 0
      },
      {
        "name": "Pollux",
        "mass": 1500,
        "radius": 6,
        "color": 0xf4a261,
        "x": 16,
        "z": 0
      }
    ],
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 13,
      "z": 43
    },
    "goal": {
      "x": 28,
      "z": -44,
      "r": 5.3
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Nova",
        "mass": 2165,
        "radius": 6.1,
        "color": 0xffc8dd,
        "x": 19,
        "z": 9
      },
      {
        "name": "Onyx",
        "mass": 921,
        "radius": 5.2,
        "color": 0x95d5b2,
        "x": -38,
        "z": 9
      },
      {
        "name": "Atlas",
        "mass": 641,
        "radius": 4.3,
        "color": 0x7ae582,
        "x": 41,
        "z": -25
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -2,
        "z": -22
      }
    ],
    "pickups": [
      {
        "x": 28,
        "z": -11,
        "fuel": 1.5
      }
    ],
    "name": "Wreckage Field",
    "hint": "Derelict ships drift in the lanes now — one touch and it's over.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": -22,
      "z": 43
    },
    "goal": {
      "x": 6,
      "z": -44,
      "r": 5.2
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Iris",
        "mass": 1742,
        "radius": 6.1,
        "color": 0xbde0fe,
        "x": -6,
        "z": -4
      },
      {
        "name": "Juno",
        "mass": 1407,
        "radius": 5,
        "color": 0x8ecae6,
        "x": 36,
        "z": -7
      },
      {
        "name": "Basil",
        "mass": 882,
        "radius": 5.4,
        "color": 0x7ae582,
        "x": -20,
        "z": -15
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 22,
        "z": 11
      }
    ],
    "pickups": [
      {
        "x": -4,
        "z": 12,
        "fuel": 1.5
      }
    ],
    "name": "Double Trouble",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 13,
      "z": 43
    },
    "goal": {
      "x": 20,
      "z": -44,
      "r": 5.3
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Halo",
        "mass": 1630,
        "radius": 6.5,
        "color": 0xffd166,
        "x": 23,
        "z": 11
      },
      {
        "name": "Zephyr",
        "mass": 834,
        "radius": 4.3,
        "color": 0x8ecae6,
        "x": -19,
        "z": 31
      },
      {
        "name": "Nimbus",
        "mass": 988,
        "radius": 4.2,
        "color": 0xffc8dd,
        "x": -31,
        "z": 0
      },
      {
        "name": "Ember",
        "mass": 845,
        "radius": 3.8,
        "color": 0xffd166,
        "x": -10,
        "z": -3
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 29,
        "z": 29
      },
      {
        "radius": 2,
        "x": -25,
        "z": 21
      }
    ],
    "pickups": [
      {
        "x": 15,
        "z": -13,
        "fuel": 1.5
      }
    ],
    "name": "The Long Way",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 22,
      "z": 43
    },
    "goal": {
      "x": -16,
      "z": -44,
      "r": 5.5
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Vesta",
        "mass": 1941,
        "radius": 6.2,
        "color": 0x7ae582,
        "x": 0,
        "z": 0
      },
      {
        "name": "Nimbus",
        "mass": 878,
        "radius": 3.7,
        "color": 0xc8b6ff,
        "x": -9,
        "z": -21
      },
      {
        "name": "Pip",
        "mass": 828,
        "radius": 4.2,
        "color": 0xbde0fe,
        "x": 11,
        "z": -15
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 4,
        "z": 18
      },
      {
        "radius": 2,
        "x": 28,
        "z": 17
      }
    ],
    "pickups": [
      {
        "x": -16,
        "z": -6,
        "fuel": 1.5
      }
    ],
    "name": "Whiplash",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": -25,
      "z": 43
    },
    "goal": {
      "x": -15,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 47,
    "fuel": 3,
    "bodies": [
      {
        "name": "Lumen",
        "mass": 2362,
        "radius": 6.8,
        "color": 0xffd166,
        "x": -15,
        "z": -12
      },
      {
        "name": "Pip",
        "mass": 1381,
        "radius": 3.9,
        "color": 0xffd166,
        "x": 13,
        "z": 26
      },
      {
        "name": "Nimbus",
        "mass": 1162,
        "radius": 4.9,
        "color": 0xffc8dd,
        "x": -10,
        "z": 9
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 31,
        "z": 9
      },
      {
        "radius": 2,
        "x": -30,
        "z": 18
      },
      {
        "radius": 2,
        "patrol": {
          "x1": 10,
          "z1": -18,
          "x2": 24,
          "z2": -11,
          "period": 7.9,
          "phase": 0.59
        }
      }
    ],
    "pickups": [
      {
        "x": -24,
        "z": 13,
        "fuel": 1.5
      }
    ],
    "name": "Picket Line",
    "hint": "That ship is on patrol. Watch its route before you launch.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 20,
      "z": 43
    },
    "goal": {
      "x": 10,
      "z": -44,
      "r": 5.2
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Atlas",
        "mass": 1638,
        "radius": 6.8,
        "color": 0xffc8dd,
        "x": 24,
        "z": 4
      },
      {
        "name": "Opal",
        "mass": 610,
        "radius": 4.3,
        "color": 0xffc8dd,
        "x": 31,
        "z": -14
      },
      {
        "name": "Mint",
        "mass": 1315,
        "radius": 4.5,
        "color": 0xffd166,
        "x": -20,
        "z": 15
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 31,
        "z": 19
      },
      {
        "radius": 2,
        "x": 18,
        "z": 23
      },
      {
        "radius": 2,
        "patrol": {
          "x1": -2,
          "z1": 8,
          "x2": 12,
          "z2": 25,
          "period": 4.2,
          "phase": 0.21
        }
      }
    ],
    "pickups": [
      {
        "x": 8,
        "z": 9,
        "fuel": 1.5
      }
    ],
    "name": "Gravity Assist",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 7,
      "z": 43
    },
    "goal": {
      "x": 6,
      "z": -44,
      "r": 5.3
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Pip",
        "mass": 2336,
        "radius": 7.1,
        "color": 0x90e0ef,
        "x": 7,
        "z": -6
      },
      {
        "name": "Ember",
        "mass": 697,
        "radius": 3.6,
        "color": 0xbde0fe,
        "x": -9,
        "z": -24
      },
      {
        "name": "Juno",
        "mass": 1182,
        "radius": 4.7,
        "color": 0xff8fa3,
        "x": -22,
        "z": 13
      },
      {
        "name": "Lyra",
        "mass": 874,
        "radius": 4.3,
        "color": 0x7ae582,
        "x": -27,
        "z": -29
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -16,
        "z": -7
      },
      {
        "radius": 2,
        "x": -21,
        "z": -3
      },
      {
        "radius": 2,
        "orbit": {
          "cx": 9,
          "cz": -5,
          "radius": 14.2,
          "omega": 0.55,
          "phase": 0.95
        }
      }
    ],
    "pickups": [
      {
        "x": 15,
        "z": 2,
        "fuel": 1.5
      }
    ],
    "name": "Full Send",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 60,
    "ship": {
      "x": 10,
      "z": 43
    },
    "goal": {
      "x": -25,
      "z": -44,
      "r": 5.4
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Pebble",
        "mass": 2112,
        "radius": 6.5,
        "color": 0x8ecae6,
        "x": -5,
        "z": 4
      },
      {
        "name": "Sage",
        "mass": 936,
        "radius": 5.5,
        "color": 0xffc8dd,
        "x": 32,
        "z": -6
      },
      {
        "name": "Juno",
        "mass": 1273,
        "radius": 4.5,
        "color": 0xf4a261,
        "x": 9,
        "z": -22
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 35,
        "z": -23
      },
      {
        "radius": 2,
        "x": -26,
        "z": 27
      },
      {
        "radius": 2,
        "orbit": {
          "cx": -3,
          "cz": 12,
          "radius": 18.8,
          "omega": 0.49,
          "phase": 2.62
        }
      }
    ],
    "pickups": [
      {
        "x": -16,
        "z": -8,
        "fuel": 1.5
      }
    ],
    "name": "Masterclass",
    "hint": "Big wells block the way. Dive in and let gravity throw you.",
    "difficulty": 2
  },
  {
    "name": "Repulsor Ridge",
    "hint": "That hill pushes you AWAY. Ride the pass between the hill and the well.",
    "extent": 62,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Nope",
        "mass": -1200,
        "radius": 4.5,
        "color": 0xff6b35,
        "x": -12,
        "z": 0
      },
      {
        "name": "Anchor",
        "mass": 1300,
        "radius": 5,
        "color": 0x90e0ef,
        "x": 16,
        "z": -2
      }
    ],
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 18,
      "z": 45
    },
    "goal": {
      "x": 2,
      "z": -45,
      "r": 5.3
    },
    "maxLaunch": 47,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Static",
        "mass": -1742,
        "radius": 4.2,
        "color": 0xff6b35,
        "x": 25,
        "z": 12
      },
      {
        "name": "Echo",
        "mass": 1107,
        "radius": 4.7,
        "color": 0x7ae582,
        "x": -16,
        "z": 23
      },
      {
        "name": "Lyra",
        "mass": 1393,
        "radius": 4.1,
        "color": 0xffc8dd,
        "x": 13,
        "z": -4
      }
    ],
    "pickups": [
      {
        "x": 12,
        "z": 6,
        "fuel": 1.5
      }
    ],
    "name": "The Pass",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 2,
      "z": 45
    },
    "goal": {
      "x": -11,
      "z": -45,
      "r": 5.1
    },
    "maxLaunch": 46,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Pusher",
        "mass": -1292,
        "radius": 4.2,
        "color": 0xff6b35,
        "x": -22,
        "z": -4
      },
      {
        "name": "Koa",
        "mass": 1265,
        "radius": 5,
        "color": 0x7ae582,
        "x": -11,
        "z": -26
      },
      {
        "name": "Juno",
        "mass": 1557,
        "radius": 4.9,
        "color": 0x7ae582,
        "x": 27,
        "z": 6
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 21,
        "z": -25
      }
    ],
    "pickups": [
      {
        "x": -1,
        "z": -7,
        "fuel": 1.5
      }
    ],
    "name": "Push and Pull",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 17,
      "z": 45
    },
    "goal": {
      "x": 10,
      "z": -45,
      "r": 5.4
    },
    "maxLaunch": 49,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Shove",
        "mass": -1133,
        "radius": 5,
        "color": 0xff6b35,
        "x": 24,
        "z": -15
      },
      {
        "name": "Quartz",
        "mass": 775,
        "radius": 4,
        "color": 0x7ae582,
        "x": -9,
        "z": -4
      },
      {
        "name": "Iris",
        "mass": 1315,
        "radius": 3.8,
        "color": 0xf4a261,
        "x": 42,
        "z": -29
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -35,
        "z": 8
      }
    ],
    "pickups": [
      {
        "x": 14,
        "z": 4,
        "fuel": 1.5
      }
    ],
    "name": "Ridge Runner",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 17,
      "z": 45
    },
    "goal": {
      "x": 3,
      "z": -45,
      "r": 4.8
    },
    "maxLaunch": 47,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Bristle",
        "mass": -941,
        "radius": 4.5,
        "color": 0xff6b35,
        "x": -8,
        "z": 2
      },
      {
        "name": "Onyx",
        "mass": 859,
        "radius": 4.5,
        "color": 0x95d5b2,
        "x": 4,
        "z": -7
      },
      {
        "name": "Frost",
        "mass": 1518,
        "radius": 3.9,
        "color": 0xf4a261,
        "x": -2,
        "z": 29
      }
    ],
    "waypoints": [
      {
        "x": 17,
        "z": 2,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 13,
        "z": 26
      }
    ],
    "pickups": [
      {
        "x": 16,
        "z": -16,
        "fuel": 1.5
      }
    ],
    "name": "Waystation",
    "hint": "Dock at the station 🛰 first — it refuels you for the next leg.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": -13,
      "z": 45
    },
    "goal": {
      "x": 19,
      "z": -45,
      "r": 5
    },
    "maxLaunch": 47,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Static",
        "mass": -1162,
        "radius": 4.4,
        "color": 0xff6b35,
        "x": 3,
        "z": 21
      },
      {
        "name": "Dune",
        "mass": 1307,
        "radius": 5.2,
        "color": 0x90e0ef,
        "x": 10,
        "z": -7
      },
      {
        "name": "Vesta",
        "mass": 1376,
        "radius": 5.1,
        "color": 0x7ae582,
        "x": -25,
        "z": 20
      },
      {
        "name": "Pip",
        "mass": 1093,
        "radius": 4.3,
        "color": 0xffc8dd,
        "x": 23,
        "z": -24
      }
    ],
    "waypoints": [
      {
        "x": -9,
        "z": 3,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 35,
        "z": -25
      }
    ],
    "pickups": [
      {
        "x": -6,
        "z": 18,
        "fuel": 1.5
      }
    ],
    "name": "Backpressure",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 1,
      "z": 45
    },
    "goal": {
      "x": 4,
      "z": -45,
      "r": 4.9
    },
    "maxLaunch": 46,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Static",
        "mass": -1277,
        "radius": 4.5,
        "color": 0xff6b35,
        "x": 5,
        "z": 17
      },
      {
        "name": "Mica",
        "mass": 979,
        "radius": 4.7,
        "color": 0xf4a261,
        "x": -10,
        "z": -33
      },
      {
        "name": "Juno",
        "mass": 741,
        "radius": 4.2,
        "color": 0xffc8dd,
        "x": -6,
        "z": -12
      },
      {
        "name": "Ember",
        "mass": 1352,
        "radius": 4.9,
        "color": 0x95d5b2,
        "x": -23,
        "z": 28
      }
    ],
    "waypoints": [
      {
        "x": -17,
        "z": -2,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -34,
        "z": 12
      },
      {
        "radius": 2,
        "patrol": {
          "x1": -35,
          "z1": 18,
          "x2": -47,
          "z2": 5,
          "period": 6.9,
          "phase": 0.66
        }
      }
    ],
    "pickups": [
      {
        "x": -9,
        "z": 21,
        "fuel": 1.5
      }
    ],
    "name": "Crosswind",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 5,
      "z": 45
    },
    "goal": {
      "x": -19,
      "z": -45,
      "r": 5.1
    },
    "maxLaunch": 47,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Bristle",
        "mass": -1218,
        "radius": 4.1,
        "color": 0xff6b35,
        "x": 12,
        "z": -10
      },
      {
        "name": "Koa",
        "mass": 1431,
        "radius": 4.2,
        "color": 0x95d5b2,
        "x": -39,
        "z": 32
      },
      {
        "name": "Rhea",
        "mass": 981,
        "radius": 4.5,
        "color": 0x95d5b2,
        "x": -29,
        "z": 13
      },
      {
        "name": "Iris",
        "mass": 1078,
        "radius": 3.9,
        "color": 0xf4a261,
        "x": 23,
        "z": 20
      }
    ],
    "waypoints": [
      {
        "x": -5,
        "z": 5,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 9,
          "z1": 8,
          "x2": -7,
          "z2": 23,
          "period": 7.3,
          "phase": 0.31
        }
      }
    ],
    "pickups": [
      {
        "x": -5,
        "z": -18,
        "fuel": 1.5
      }
    ],
    "name": "The Squeeze",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": -22,
      "z": 45
    },
    "goal": {
      "x": 24,
      "z": -45,
      "r": 5
    },
    "maxLaunch": 44,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Shove",
        "mass": -1499,
        "radius": 4.6,
        "color": 0xff6b35,
        "x": -9,
        "z": 2
      },
      {
        "name": "Pusher",
        "mass": -1306,
        "radius": 4.4,
        "color": 0xff6b35,
        "x": -11,
        "z": 18
      },
      {
        "name": "Rhea",
        "mass": 1367,
        "radius": 3.9,
        "color": 0xc8b6ff,
        "x": 38,
        "z": 28
      },
      {
        "name": "Koa",
        "mass": 1290,
        "radius": 4.3,
        "color": 0x7ae582,
        "x": 30,
        "z": -19
      },
      {
        "name": "Iris",
        "mass": 1024,
        "radius": 3.6,
        "color": 0xc8b6ff,
        "x": -10,
        "z": -23
      }
    ],
    "waypoints": [
      {
        "x": 18,
        "z": 11,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -30,
        "z": 28
      },
      {
        "radius": 2,
        "orbit": {
          "cx": 16,
          "cz": 10,
          "radius": 19.8,
          "omega": 0.41,
          "phase": 3.57
        }
      }
    ],
    "pickups": [
      {
        "x": 15,
        "z": -15,
        "fuel": 1.5
      }
    ],
    "name": "Turbulence",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 62,
    "ship": {
      "x": 27,
      "z": 45
    },
    "goal": {
      "x": 20,
      "z": -45,
      "r": 4.9
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Pusher",
        "mass": -1207,
        "radius": 4.8,
        "color": 0xff6b35,
        "x": 34,
        "z": -18
      },
      {
        "name": "Dune",
        "mass": 952,
        "radius": 5.5,
        "color": 0xff8fa3,
        "x": -15,
        "z": 13
      },
      {
        "name": "Iris",
        "mass": 1517,
        "radius": 4.6,
        "color": 0x95d5b2,
        "x": -41,
        "z": 6
      }
    ],
    "waypoints": [
      {
        "x": 26,
        "z": -3,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "orbit": {
          "cx": -12,
          "cz": 16,
          "radius": 19.7,
          "omega": 0.68,
          "phase": 3.02
        }
      }
    ],
    "pickups": [
      {
        "x": 26,
        "z": 25,
        "fuel": 1.5
      }
    ],
    "name": "Summit",
    "hint": "Orange hills push you away. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "name": "Moonshot",
    "hint": "The moon keeps moving — even while you aim. Time your release!",
    "extent": 62,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -46,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Aegis",
        "mass": 2200,
        "radius": 7,
        "color": 0xbde0fe,
        "x": 0,
        "z": -4
      },
      {
        "name": "Luna",
        "mass": 520,
        "radius": 3,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 20,
          "omega": 0.7,
          "phase": 0.8
        }
      }
    ],
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -23,
      "z": 46
    },
    "goal": {
      "x": 12,
      "z": -47,
      "r": 4.9
    },
    "maxLaunch": 45,
    "fuel": 4,
    "bodies": [
      {
        "name": "Opal",
        "mass": 1103,
        "radius": 4.9,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -4,
          "cz": -3,
          "radius": 10.6,
          "omega": -0.32,
          "phase": 6.19
        }
      },
      {
        "name": "Coral",
        "mass": 1382,
        "radius": 5.2,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -4,
          "cz": -3,
          "radius": 10.6,
          "omega": -0.32,
          "phase": 9.33
        }
      },
      {
        "name": "Vesta",
        "mass": 1048,
        "radius": 4.1,
        "color": 0x95d5b2,
        "x": 30,
        "z": -17
      },
      {
        "name": "Frost",
        "mass": 635,
        "radius": 3.9,
        "color": 0x95d5b2,
        "x": -7,
        "z": -36
      }
    ],
    "pickups": [
      {
        "x": -36,
        "z": -8,
        "fuel": 1.5
      }
    ],
    "name": "Orbit Window",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -13,
      "z": 46
    },
    "goal": {
      "x": 13,
      "z": -47,
      "r": 5.1
    },
    "maxLaunch": 42,
    "fuel": 4,
    "bodies": [
      {
        "name": "Nova",
        "mass": 1312,
        "radius": 4.7,
        "color": 0xf4a261,
        "orbit": {
          "cx": 12,
          "cz": -9,
          "radius": 13.6,
          "omega": -0.53,
          "phase": 3.77
        }
      },
      {
        "name": "Basil",
        "mass": 1096,
        "radius": 4.8,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 12,
          "cz": -9,
          "radius": 13.6,
          "omega": -0.53,
          "phase": 6.91
        }
      },
      {
        "name": "Mint",
        "mass": 960,
        "radius": 4.8,
        "color": 0xffc8dd,
        "x": -35,
        "z": 32
      }
    ],
    "pickups": [
      {
        "x": -17,
        "z": -14,
        "fuel": 1.5
      }
    ],
    "name": "Waltz",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": 0,
      "z": 46
    },
    "goal": {
      "x": -2,
      "z": -47,
      "r": 4.8
    },
    "maxLaunch": 47,
    "fuel": 4,
    "bodies": [
      {
        "name": "Juno",
        "mass": 1195,
        "radius": 5,
        "color": 0x8ecae6,
        "orbit": {
          "cx": -10,
          "cz": 5,
          "radius": 14.8,
          "omega": 0.54,
          "phase": 2.07
        }
      },
      {
        "name": "Dune",
        "mass": 1352,
        "radius": 4.8,
        "color": 0xbde0fe,
        "orbit": {
          "cx": -10,
          "cz": 5,
          "radius": 14.8,
          "omega": 0.54,
          "phase": 5.21
        }
      },
      {
        "name": "Iris",
        "mass": 798,
        "radius": 3.8,
        "color": 0xc8b6ff,
        "x": 20,
        "z": 21
      }
    ],
    "waypoints": [
      {
        "x": 19,
        "z": 0,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": -22,
        "z": -22,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": 11,
        "z": 29,
        "fuel": 1.5
      }
    ],
    "name": "First Haul",
    "hint": "Grab the cargo 📦, then haul it to the dropoff 📥. It's heavy — thrusters suffer.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -21,
      "z": 46
    },
    "goal": {
      "x": 26,
      "z": -47,
      "r": 4.9
    },
    "maxLaunch": 45,
    "fuel": 4,
    "bodies": [
      {
        "name": "Basil",
        "mass": 1059,
        "radius": 4.9,
        "color": 0xff8fa3,
        "orbit": {
          "cx": -7,
          "cz": 6,
          "radius": 13.5,
          "omega": 0.34,
          "phase": 0.98
        }
      },
      {
        "name": "Lumen",
        "mass": 1117,
        "radius": 5.4,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -7,
          "cz": 6,
          "radius": 13.5,
          "omega": 0.34,
          "phase": 4.12
        }
      },
      {
        "name": "Vesta",
        "mass": 1072,
        "radius": 4.6,
        "color": 0x90e0ef,
        "x": 22,
        "z": -9
      }
    ],
    "waypoints": [
      {
        "x": 18,
        "z": 16,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": 0,
        "z": -21,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -3,
        "z": 35,
        "fuel": 1.5
      }
    ],
    "name": "Pendulum",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -14,
      "z": 46
    },
    "goal": {
      "x": -3,
      "z": -47,
      "r": 4.9
    },
    "maxLaunch": 43,
    "fuel": 4,
    "bodies": [
      {
        "name": "Onyx",
        "mass": 1125,
        "radius": 5.3,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -5,
          "cz": -7,
          "radius": 10.2,
          "omega": 0.49,
          "phase": 3.74
        }
      },
      {
        "name": "Mica",
        "mass": 1293,
        "radius": 4.9,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -5,
          "cz": -7,
          "radius": 10.2,
          "omega": 0.49,
          "phase": 6.88
        }
      },
      {
        "name": "Frost",
        "mass": 650,
        "radius": 3.6,
        "color": 0xffc8dd,
        "x": -21,
        "z": 29
      },
      {
        "name": "Pebble",
        "mass": 760,
        "radius": 3.8,
        "color": 0x7ae582,
        "x": 16,
        "z": 15
      }
    ],
    "waypoints": [
      {
        "x": -21,
        "z": 15,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": -26,
        "z": -21,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 37,
          "z1": 16,
          "x2": 53,
          "z2": 10,
          "period": 4.7,
          "phase": 0.15
        }
      }
    ],
    "pickups": [
      {
        "x": -27,
        "z": -10,
        "fuel": 1.5
      }
    ],
    "name": "Metronome",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -1,
      "z": 46
    },
    "goal": {
      "x": 11,
      "z": -47,
      "r": 4.9
    },
    "maxLaunch": 47,
    "fuel": 4,
    "bodies": [
      {
        "name": "Ember",
        "mass": 1128,
        "radius": 4.7,
        "color": 0xff8fa3,
        "orbit": {
          "cx": -7,
          "cz": -9,
          "radius": 14.2,
          "omega": -0.45,
          "phase": 5.69
        }
      },
      {
        "name": "Nova",
        "mass": 1106,
        "radius": 5.2,
        "color": 0xff8fa3,
        "orbit": {
          "cx": -7,
          "cz": -9,
          "radius": 14.2,
          "omega": -0.45,
          "phase": 8.83
        }
      },
      {
        "name": "Jasper",
        "mass": 1221,
        "radius": 3.9,
        "color": 0xbde0fe,
        "x": 37,
        "z": -11
      }
    ],
    "waypoints": [
      {
        "x": -18,
        "z": 18,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": 22,
        "z": -10,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 18,
          "z1": -25,
          "x2": -2,
          "z2": -34,
          "period": 6.5,
          "phase": 0.37
        }
      }
    ],
    "pickups": [
      {
        "x": -8,
        "z": 32,
        "fuel": 1.5
      },
      {
        "x": 5,
        "z": 26,
        "fuel": 1.5
      }
    ],
    "name": "Eclipse",
    "hint": "Gravity assist: launch when a moving body can sling you forward, not against you.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": 26,
      "z": 46
    },
    "goal": {
      "x": -17,
      "z": -47,
      "r": 5.1
    },
    "maxLaunch": 46,
    "fuel": 4,
    "bodies": [
      {
        "name": "Dune",
        "mass": 1390,
        "radius": 5.4,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -1,
          "cz": 1,
          "radius": 11.3,
          "omega": -0.53,
          "phase": 0.04
        }
      },
      {
        "name": "Jasper",
        "mass": 1134,
        "radius": 5.2,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -1,
          "cz": 1,
          "radius": 11.3,
          "omega": -0.53,
          "phase": 3.18
        }
      },
      {
        "name": "Fern",
        "mass": 793,
        "radius": 4.4,
        "color": 0xbde0fe,
        "x": 20,
        "z": -29
      }
    ],
    "waypoints": [
      {
        "x": 26,
        "z": 2,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": -22,
        "z": -16,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 13,
          "z1": 22,
          "x2": 34,
          "z2": 22,
          "period": 6.3,
          "phase": 0.26
        }
      }
    ],
    "pickups": [
      {
        "x": 11,
        "z": -18,
        "fuel": 1.5
      },
      {
        "x": -22,
        "z": -28,
        "fuel": 1.5
      }
    ],
    "name": "Revolution",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": -27,
      "z": 46
    },
    "goal": {
      "x": -9,
      "z": -47,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 4,
    "bodies": [
      {
        "name": "Ember",
        "mass": 1274,
        "radius": 5.5,
        "color": 0xff8fa3,
        "orbit": {
          "cx": -11,
          "cz": 4,
          "radius": 10.2,
          "omega": -0.33,
          "phase": 6.15
        }
      },
      {
        "name": "Lumen",
        "mass": 1152,
        "radius": 5.1,
        "color": 0xffd166,
        "orbit": {
          "cx": -11,
          "cz": 4,
          "radius": 10.2,
          "omega": -0.33,
          "phase": 9.29
        }
      },
      {
        "name": "Pip",
        "mass": 940,
        "radius": 4.7,
        "color": 0x90e0ef,
        "x": 27,
        "z": -1
      },
      {
        "name": "Quartz",
        "mass": 571,
        "radius": 4.2,
        "color": 0xffd166,
        "x": 25,
        "z": 29
      }
    ],
    "waypoints": [
      {
        "x": -35,
        "z": 6,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": 5,
        "z": -16,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": -27,
          "z1": 26,
          "x2": -48,
          "z2": 28,
          "period": 7.5,
          "phase": 0.89
        }
      }
    ],
    "pickups": [
      {
        "x": -4,
        "z": -23,
        "fuel": 1.5
      },
      {
        "x": -31,
        "z": 36,
        "fuel": 1.5
      }
    ],
    "name": "Perfect Timing",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 64,
    "ship": {
      "x": 26,
      "z": 46
    },
    "goal": {
      "x": -28,
      "z": -47,
      "r": 5.2
    },
    "maxLaunch": 43,
    "fuel": 4,
    "bodies": [
      {
        "name": "Fern",
        "mass": 1319,
        "radius": 5,
        "color": 0x7ae582,
        "orbit": {
          "cx": 3,
          "cz": -13,
          "radius": 12.2,
          "omega": -0.53,
          "phase": 1.41
        }
      },
      {
        "name": "Juno",
        "mass": 1241,
        "radius": 4.8,
        "color": 0xff8fa3,
        "orbit": {
          "cx": 3,
          "cz": -13,
          "radius": 12.2,
          "omega": -0.53,
          "phase": 4.55
        }
      },
      {
        "name": "Frost",
        "mass": 1013,
        "radius": 4.4,
        "color": 0xffc8dd,
        "x": 22,
        "z": -34
      }
    ],
    "waypoints": [
      {
        "x": 19,
        "z": 7,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": -24,
        "z": -5,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 27,
          "z1": -8,
          "x2": 42,
          "z2": 8,
          "period": 6.9,
          "phase": 0.49
        }
      }
    ],
    "pickups": [
      {
        "x": 28,
        "z": 31,
        "fuel": 1.5
      },
      {
        "x": -42,
        "z": -28,
        "fuel": 1.5
      }
    ],
    "name": "Clockwork",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "name": "Event Horizon",
    "hint": "Nothing escapes the red ring. Skim close for a huge slingshot — but not TOO close.",
    "extent": 64,
    "ship": {
      "x": -38,
      "z": 44
    },
    "goal": {
      "x": 34,
      "z": -44,
      "r": 4.5
    },
    "maxLaunch": 44,
    "fuel": 4,
    "bodies": [
      {
        "name": "Maw",
        "mass": 5200,
        "radius": 3.5,
        "horizon": 6.5,
        "color": 0x1a1a2e,
        "x": 0,
        "z": 0,
        "type": "blackhole"
      }
    ],
    "difficulty": 5
  },
  {
    "name": "Grand Tour",
    "hint": "Everything at once. Take your time — plot the long way round.",
    "extent": 74,
    "ship": {
      "x": 30,
      "z": 56
    },
    "goal": {
      "x": -34,
      "z": -50,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Titan",
        "mass": 1700,
        "radius": 6,
        "color": 0xffd166,
        "x": 26,
        "z": 14
      },
      {
        "name": "Wisp",
        "mass": 420,
        "radius": 2.5,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 15,
          "omega": 0.8,
          "phase": 2.1
        }
      },
      {
        "name": "Nope II",
        "mass": -1600,
        "radius": 4.5,
        "color": 0xff6b35,
        "x": 2,
        "z": -4
      },
      {
        "name": "Maw II",
        "mass": 4200,
        "radius": 3,
        "horizon": 5.5,
        "color": 0x1a1a2e,
        "x": -26,
        "z": -18,
        "type": "blackhole"
      }
    ],
    "difficulty": 5
  },
  {
    "extent": 68,
    "ship": {
      "x": 29,
      "z": 49
    },
    "goal": {
      "x": -22,
      "z": -50,
      "r": 4.4
    },
    "maxLaunch": 40,
    "fuel": 5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 3100,
        "radius": 9.4,
        "color": 0xff9e6b,
        "x": -3,
        "z": 2,
        "type": "sun"
      },
      {
        "name": "Halo",
        "mass": 729,
        "radius": 4.2,
        "color": 0x8ecae6,
        "orbit": {
          "cx": -3,
          "cz": 2,
          "radius": 21,
          "omega": 0.52,
          "phase": 0.47
        }
      },
      {
        "name": "Atlas",
        "mass": 753,
        "radius": 4.8,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -3,
          "cz": 2,
          "radius": 38,
          "omega": -0.34,
          "phase": 1.78
        }
      }
    ],
    "pickups": [
      {
        "x": 46,
        "z": 16,
        "fuel": 1.5
      }
    ],
    "name": "Star System",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 67,
    "ship": {
      "x": 22,
      "z": 48
    },
    "goal": {
      "x": -29,
      "z": -49,
      "r": 4.2
    },
    "maxLaunch": 42,
    "fuel": 5,
    "bodies": [
      {
        "name": "Vera",
        "mass": 2868,
        "radius": 9.4,
        "color": 0xffd166,
        "x": -3,
        "z": -5,
        "type": "sun"
      },
      {
        "name": "Iris",
        "mass": 688,
        "radius": 4.2,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -3,
          "cz": -5,
          "radius": 21,
          "omega": -0.37,
          "phase": 2.3
        }
      },
      {
        "name": "Cinder",
        "mass": 731,
        "radius": 3.8,
        "color": 0xf4a261,
        "orbit": {
          "cx": -3,
          "cz": -5,
          "radius": 38,
          "omega": 0.39,
          "phase": 0.92
        }
      }
    ],
    "name": "Dark Passage",
    "hint": "Your engine can't brute-force this one. Wait for a planet to swing by and steal its momentum.",
    "difficulty": 5
  },
  {
    "extent": 72,
    "ship": {
      "x": -19,
      "z": 52
    },
    "goal": {
      "x": 7,
      "z": -53,
      "r": 4.5
    },
    "maxLaunch": 40,
    "fuel": 5,
    "bodies": [
      {
        "name": "Vera",
        "mass": 2608,
        "radius": 9.4,
        "color": 0xff9e6b,
        "x": 5,
        "z": 1,
        "type": "sun"
      },
      {
        "name": "Vesta",
        "mass": 904,
        "radius": 4.5,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": 5,
          "cz": 1,
          "radius": 21,
          "omega": -0.39,
          "phase": 4.91
        }
      },
      {
        "name": "Jasper",
        "mass": 545,
        "radius": 4.2,
        "color": 0xff8fa3,
        "orbit": {
          "cx": 5,
          "cz": 1,
          "radius": 38,
          "omega": 0.46,
          "phase": 1.65
        }
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": -42,
          "z1": 14,
          "x2": -60,
          "z2": 7,
          "period": 7.6,
          "phase": 0.74
        }
      }
    ],
    "pickups": [
      {
        "x": -17,
        "z": -19,
        "fuel": 1.5
      }
    ],
    "name": "Planetfall",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 72,
    "ship": {
      "x": 17,
      "z": 52
    },
    "goal": {
      "x": 19,
      "z": -53,
      "r": 4.6
    },
    "maxLaunch": 38,
    "fuel": 5,
    "bodies": [
      {
        "name": "Helios",
        "mass": 2804,
        "radius": 8.3,
        "color": 0xff9e6b,
        "x": -7,
        "z": -6,
        "type": "sun"
      },
      {
        "name": "Ember",
        "mass": 760,
        "radius": 3.9,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -7,
          "cz": -6,
          "radius": 21,
          "omega": 0.28,
          "phase": 5.98
        }
      },
      {
        "name": "Koa",
        "mass": 1016,
        "radius": 4.2,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -7,
          "cz": -6,
          "radius": 38,
          "omega": 0.34,
          "phase": 1.83
        }
      }
    ],
    "waypoints": [
      {
        "x": 39,
        "z": 20,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": 41,
        "z": -22,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": 25,
        "z": 37,
        "fuel": 1.5
      },
      {
        "x": 30,
        "z": -40,
        "fuel": 1.5
      }
    ],
    "name": "The Gauntlet",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 72,
    "ship": {
      "x": 23,
      "z": 52
    },
    "goal": {
      "x": 25,
      "z": -53,
      "r": 4.2
    },
    "maxLaunch": 38,
    "fuel": 5,
    "bodies": [
      {
        "name": "Sol",
        "mass": 3389,
        "radius": 9.2,
        "color": 0xffd166,
        "x": 4,
        "z": 0,
        "type": "sun"
      },
      {
        "name": "Basil",
        "mass": 635,
        "radius": 4.9,
        "color": 0x7ae582,
        "orbit": {
          "cx": 4,
          "cz": 0,
          "radius": 21,
          "omega": 0.52,
          "phase": 0.51
        }
      },
      {
        "name": "Vesta",
        "mass": 592,
        "radius": 3.7,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 4,
          "cz": 0,
          "radius": 38,
          "omega": 0.29,
          "phase": 3.97
        }
      }
    ],
    "waypoints": [
      {
        "x": 45,
        "z": 31,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": 47,
        "z": -32,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": 32,
        "z": 43,
        "fuel": 1.5
      },
      {
        "x": 57,
        "z": 3,
        "fuel": 1.5
      }
    ],
    "name": "Singularity",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 67,
    "ship": {
      "x": -11,
      "z": 48
    },
    "goal": {
      "x": -30,
      "z": -49,
      "r": 4.5
    },
    "maxLaunch": 39,
    "fuel": 5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 3368,
        "radius": 8.3,
        "color": 0xff9e6b,
        "x": 3,
        "z": -8,
        "type": "sun"
      },
      {
        "name": "Rhea",
        "mass": 986,
        "radius": 3.9,
        "color": 0xffd166,
        "orbit": {
          "cx": 3,
          "cz": -8,
          "radius": 21,
          "omega": 0.31,
          "phase": 1.29
        }
      },
      {
        "name": "Sage",
        "mass": 593,
        "radius": 3.7,
        "color": 0xf4a261,
        "orbit": {
          "cx": 3,
          "cz": -8,
          "radius": 38,
          "omega": -0.44,
          "phase": 1.35
        }
      }
    ],
    "waypoints": [
      {
        "x": -36,
        "z": 27,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": -46,
        "z": -17,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -25,
        "z": 37,
        "fuel": 1.5
      },
      {
        "x": -45,
        "z": 7,
        "fuel": 1.5
      }
    ],
    "name": "Far Shore",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 74,
    "ship": {
      "x": 10,
      "z": 53
    },
    "goal": {
      "x": 35,
      "z": -54,
      "r": 4.3
    },
    "maxLaunch": 39,
    "fuel": 5,
    "bodies": [
      {
        "name": "Helios",
        "mass": 3502,
        "radius": 9.2,
        "color": 0xff9e6b,
        "x": 1,
        "z": -5,
        "type": "sun"
      },
      {
        "name": "Halo",
        "mass": 684,
        "radius": 5,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 1,
          "cz": -5,
          "radius": 21,
          "omega": -0.44,
          "phase": 0.49
        }
      },
      {
        "name": "Dune",
        "mass": 929,
        "radius": 4.5,
        "color": 0xf4a261,
        "orbit": {
          "cx": 1,
          "cz": -5,
          "radius": 38,
          "omega": -0.41,
          "phase": 2.36
        }
      }
    ],
    "waypoints": [
      {
        "x": 38,
        "z": 31,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": 50,
        "z": -30,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": 20,
        "z": 39,
        "fuel": 1.5
      },
      {
        "x": 42,
        "z": -43,
        "fuel": 1.5
      }
    ],
    "name": "Last Light",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 73,
    "ship": {
      "x": -27,
      "z": 53
    },
    "goal": {
      "x": -15,
      "z": -53,
      "r": 4.3
    },
    "maxLaunch": 44,
    "fuel": 5,
    "bodies": [
      {
        "name": "Helios",
        "mass": 3694,
        "radius": 8.6,
        "color": 0xffb703,
        "x": 8,
        "z": 2,
        "type": "sun"
      },
      {
        "name": "Basil",
        "mass": 683,
        "radius": 4.9,
        "color": 0xf4a261,
        "orbit": {
          "cx": 8,
          "cz": 2,
          "radius": 21.5,
          "omega": -0.51,
          "phase": 3.66
        }
      },
      {
        "name": "Iris",
        "mass": 781,
        "radius": 4.8,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 8,
          "cz": 2,
          "radius": 38.5,
          "omega": 0.31,
          "phase": 3.68
        }
      }
    ],
    "waypoints": [
      {
        "x": -42,
        "z": 15,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": -39,
        "z": -24,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -36,
        "z": 34,
        "fuel": 1.5
      },
      {
        "x": -46,
        "z": -4,
        "fuel": 1.5
      }
    ],
    "name": "GravityLoop",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  }
];
