// GravityLoop — level data (50 levels in 5 themed sets of 10).
// GENERATED by tools/generate.js — edit that file and re-run:
//   node tools/generate.js
// Coordinates: x is right, z is toward the camera (ship starts at +z).
// mass < 0 makes a repulsor (a hill instead of a well).

export const SETS = [
  {
    "name": "Cadet Orbits",
    "difficulty": 1
  },
  {
    "name": "Slingshot Academy",
    "difficulty": 2
  },
  {
    "name": "Antimatter Belt",
    "difficulty": 3
  },
  {
    "name": "Clockwork Moons",
    "difficulty": 4
  },
  {
    "name": "Deep Space",
    "difficulty": 5
  }
];

export const LEVELS = [
  {
    "name": "Liftoff",
    "hint": "Drag back from your ship to aim — like a slingshot — then release to launch!",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 42
    },
    "goal": {
      "x": 0,
      "z": -40,
      "r": 7
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Pebble",
        "mass": 260,
        "radius": 3,
        "color": 0x8ecae6,
        "x": -34,
        "z": -4
      }
    ],
    "difficulty": 1
  },
  {
    "name": "The Dip",
    "hint": "That well will bend your shot. Watch the prediction line and aim off-center.",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 42
    },
    "goal": {
      "x": 0,
      "z": -42,
      "r": 5.5
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Mint",
        "mass": 1300,
        "radius": 5,
        "color": 0x7ae582,
        "x": 15,
        "z": 0
      }
    ],
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": -26,
      "z": 43
    },
    "goal": {
      "x": 28,
      "z": -44,
      "r": 6
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Kestrel",
        "mass": 2069,
        "radius": 6.5,
        "color": 0xffb703,
        "x": 5,
        "z": 4,
        "type": "sun"
      },
      {
        "name": "Dune",
        "mass": 895,
        "radius": 3.8,
        "color": 0x90e0ef,
        "orbit": {
          "cx": 5,
          "cz": 4,
          "radius": 19,
          "omega": -0.11,
          "phase": 5.92
        }
      },
      {
        "name": "Nova",
        "mass": 927,
        "radius": 3.8,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 5,
          "cz": 4,
          "radius": 35,
          "omega": -0.09,
          "phase": 5.15
        }
      }
    ],
    "name": "Slow Orbit",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": 22,
      "z": 43
    },
    "goal": {
      "x": 18,
      "z": -44,
      "r": 5.9
    },
    "maxLaunch": 51,
    "fuel": 3,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 1566,
        "radius": 6.5,
        "color": 0xffd166,
        "x": -5,
        "z": 0,
        "type": "sun"
      },
      {
        "name": "Sage",
        "mass": 915,
        "radius": 3.6,
        "color": 0xbde0fe,
        "orbit": {
          "cx": -5,
          "cz": 0,
          "radius": 19,
          "omega": -0.15,
          "phase": 2.33
        }
      },
      {
        "name": "Lumen",
        "mass": 565,
        "radius": 4.7,
        "color": 0x7ae582,
        "orbit": {
          "cx": -5,
          "cz": 0,
          "radius": 35,
          "omega": -0.12,
          "phase": 0.8
        }
      }
    ],
    "name": "Long Coast",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": 16,
      "z": 43
    },
    "goal": {
      "x": 29,
      "z": -44,
      "r": 5.8
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Rana",
        "mass": 2061,
        "radius": 8.3,
        "color": 0xff9e6b,
        "x": -3,
        "z": -8,
        "type": "sun"
      },
      {
        "name": "Dune",
        "mass": 482,
        "radius": 4.4,
        "color": 0xf4a261,
        "orbit": {
          "cx": -3,
          "cz": -8,
          "radius": 19,
          "omega": 0.17,
          "phase": 3.46
        }
      },
      {
        "name": "Echo",
        "mass": 608,
        "radius": 4.3,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -3,
          "cz": -8,
          "radius": 35,
          "omega": 0.09,
          "phase": 3.79
        }
      }
    ],
    "name": "Downhill Run",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": 14,
      "z": 43
    },
    "goal": {
      "x": -27,
      "z": -44,
      "r": 5.6
    },
    "maxLaunch": 51,
    "fuel": 3,
    "bodies": [
      {
        "name": "Vera",
        "mass": 1802,
        "radius": 7.6,
        "color": 0xff9e6b,
        "x": 4,
        "z": -9,
        "type": "sun"
      },
      {
        "name": "Mint",
        "mass": 786,
        "radius": 3.7,
        "color": 0xff8fa3,
        "orbit": {
          "cx": 4,
          "cz": -9,
          "radius": 19,
          "omega": 0.1,
          "phase": 0.66
        }
      },
      {
        "name": "Basil",
        "mass": 944,
        "radius": 3.5,
        "color": 0x7ae582,
        "orbit": {
          "cx": 4,
          "cz": -9,
          "radius": 35,
          "omega": -0.17,
          "phase": 4.91
        }
      }
    ],
    "name": "Easy Does It",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": -9,
      "z": 43
    },
    "goal": {
      "x": -28,
      "z": -44,
      "r": 5.5
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2066,
        "radius": 7.4,
        "color": 0xffb703,
        "x": 6,
        "z": -6,
        "type": "sun"
      },
      {
        "name": "Koa",
        "mass": 642,
        "radius": 4.8,
        "color": 0xf4a261,
        "orbit": {
          "cx": 6,
          "cz": -6,
          "radius": 19,
          "omega": -0.1,
          "phase": 5.71
        }
      },
      {
        "name": "Pebble",
        "mass": 488,
        "radius": 3.8,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 6,
          "cz": -6,
          "radius": 35,
          "omega": 0.11,
          "phase": 5.28
        }
      }
    ],
    "name": "Twin Dimples",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": 27,
      "z": 43
    },
    "goal": {
      "x": 24,
      "z": -44,
      "r": 5.4
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Sol",
        "mass": 1692,
        "radius": 6.9,
        "color": 0xffd166,
        "x": -4,
        "z": -2,
        "type": "sun"
      },
      {
        "name": "Basil",
        "mass": 735,
        "radius": 3.9,
        "color": 0x7ae582,
        "orbit": {
          "cx": -4,
          "cz": -2,
          "radius": 19,
          "omega": 0.15,
          "phase": 2.49
        }
      },
      {
        "name": "Jasper",
        "mass": 641,
        "radius": 3.8,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -4,
          "cz": -2,
          "radius": 35,
          "omega": -0.14,
          "phase": 2.69
        }
      }
    ],
    "name": "Drift Lane",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": 9,
      "z": 43
    },
    "goal": {
      "x": 23,
      "z": -44,
      "r": 5.3
    },
    "maxLaunch": 51,
    "fuel": 3,
    "bodies": [
      {
        "name": "Sol",
        "mass": 1839,
        "radius": 8,
        "color": 0xffb703,
        "x": -5,
        "z": -5,
        "type": "sun"
      },
      {
        "name": "Onyx",
        "mass": 738,
        "radius": 4.9,
        "color": 0xf4a261,
        "orbit": {
          "cx": -5,
          "cz": -5,
          "radius": 19,
          "omega": -0.15,
          "phase": 1.9
        }
      },
      {
        "name": "Coral",
        "mass": 880,
        "radius": 3.8,
        "color": 0xffd166,
        "orbit": {
          "cx": -5,
          "cz": -5,
          "radius": 35,
          "omega": 0.18,
          "phase": 4.9
        }
      }
    ],
    "name": "Warm Up",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "extent": 60,
    "ship": {
      "x": 22,
      "z": 43
    },
    "goal": {
      "x": 19,
      "z": -44,
      "r": 5.1
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Kestrel",
        "mass": 1598,
        "radius": 6.9,
        "color": 0xff9e6b,
        "x": -6,
        "z": -4,
        "type": "sun"
      },
      {
        "name": "Nova",
        "mass": 489,
        "radius": 4.7,
        "color": 0xffd166,
        "orbit": {
          "cx": -6,
          "cz": -4,
          "radius": 19,
          "omega": 0.17,
          "phase": 0.06
        }
      },
      {
        "name": "Dune",
        "mass": 535,
        "radius": 4.1,
        "color": 0xff8fa3,
        "orbit": {
          "cx": -6,
          "cz": -4,
          "radius": 35,
          "omega": 0.18,
          "phase": 4.2
        }
      }
    ],
    "name": "Graduation",
    "hint": "A little star system: every well bends your shot. Learn to read the terrain.",
    "difficulty": 1
  },
  {
    "name": "Slingshot",
    "hint": "No way through — so curve around. Dive into the well and let it fling you!",
    "extent": 60,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Rusty",
        "mass": 2100,
        "radius": 7,
        "color": 0xff8fa3,
        "x": 0,
        "z": -2
      }
    ],
    "difficulty": 2
  },
  {
    "name": "The Saddle",
    "hint": "Two wells, one ridge between them. Thread the saddle — or swing wide.",
    "extent": 62,
    "ship": {
      "x": -10,
      "z": 44
    },
    "goal": {
      "x": 4,
      "z": -44,
      "r": 4.5
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Castor",
        "mass": 1500,
        "radius": 6,
        "color": 0xffd166,
        "x": -16,
        "z": 0
      },
      {
        "name": "Pollux",
        "mass": 1500,
        "radius": 6,
        "color": 0xf4a261,
        "x": 16,
        "z": 0
      }
    ],
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": -21,
      "z": 45
    },
    "goal": {
      "x": 30,
      "z": -45,
      "r": 5.1
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Kestrel",
        "mass": 2673,
        "radius": 7.5,
        "color": 0xff9e6b,
        "x": 7,
        "z": 3,
        "type": "sun"
      },
      {
        "name": "Nova",
        "mass": 1157,
        "radius": 4.9,
        "color": 0xffd166,
        "orbit": {
          "cx": 7,
          "cz": 3,
          "radius": 19,
          "omega": 0.21,
          "phase": 2.4
        }
      },
      {
        "name": "Lyra",
        "mass": 613,
        "radius": 3.7,
        "color": 0x95d5b2,
        "orbit": {
          "cx": 7,
          "cz": 3,
          "radius": 35,
          "omega": -0.21,
          "phase": 5.39
        }
      }
    ],
    "name": "Wreckage Field",
    "hint": "Derelict ships drift in the lanes now — one touch and it's over.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": 2,
      "z": 45
    },
    "goal": {
      "x": -27,
      "z": -45,
      "r": 5.5
    },
    "maxLaunch": 46,
    "fuel": 3,
    "bodies": [
      {
        "name": "Rana",
        "mass": 2470,
        "radius": 7.4,
        "color": 0xffb703,
        "x": 5,
        "z": -7,
        "type": "sun"
      },
      {
        "name": "Juno",
        "mass": 975,
        "radius": 3.9,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": 5,
          "cz": -7,
          "radius": 19,
          "omega": -0.15,
          "phase": 4.98
        }
      },
      {
        "name": "Pip",
        "mass": 720,
        "radius": 3.6,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 5,
          "cz": -7,
          "radius": 35,
          "omega": 0.21,
          "phase": 5.12
        }
      }
    ],
    "name": "Double Trouble",
    "hint": "A heavy star blocks the way. Dive into its well and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": 24,
      "z": 45
    },
    "goal": {
      "x": 23,
      "z": -45,
      "r": 5.4
    },
    "maxLaunch": 50,
    "fuel": 3,
    "bodies": [
      {
        "name": "Helios",
        "mass": 2453,
        "radius": 8.3,
        "color": 0xffd166,
        "x": -1,
        "z": -1,
        "type": "sun"
      },
      {
        "name": "Iris",
        "mass": 578,
        "radius": 3.6,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -1,
          "cz": -1,
          "radius": 19,
          "omega": 0.16,
          "phase": 2.81
        }
      },
      {
        "name": "Jasper",
        "mass": 959,
        "radius": 4.2,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -1,
          "cz": -1,
          "radius": 35,
          "omega": 0.11,
          "phase": 2.07
        }
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -36,
        "z": 28
      },
      {
        "radius": 2,
        "x": -37,
        "z": -30
      }
    ],
    "name": "The Long Way",
    "hint": "A heavy star blocks the way. Dive into its well and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": -1,
      "z": 45
    },
    "goal": {
      "x": 27,
      "z": -45,
      "r": 5.2
    },
    "maxLaunch": 48,
    "fuel": 3,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2553,
        "radius": 6.8,
        "color": 0xffd166,
        "x": -7,
        "z": -5,
        "type": "sun"
      },
      {
        "name": "Pebble",
        "mass": 820,
        "radius": 4.1,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -7,
          "cz": -5,
          "radius": 19,
          "omega": -0.24,
          "phase": 3
        }
      },
      {
        "name": "Atlas",
        "mass": 1052,
        "radius": 3.5,
        "color": 0x8ecae6,
        "orbit": {
          "cx": -7,
          "cz": -5,
          "radius": 35,
          "omega": 0.15,
          "phase": 3.65
        }
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 30,
        "z": 18
      },
      {
        "radius": 2,
        "x": 34,
        "z": -27
      }
    ],
    "name": "Whiplash",
    "hint": "A heavy star blocks the way. Dive into its well and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": 24,
      "z": 45
    },
    "goal": {
      "x": -21,
      "z": -45,
      "r": 5.3
    },
    "maxLaunch": 46,
    "fuel": 3,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 2382,
        "radius": 8.4,
        "color": 0xff9e6b,
        "x": 0,
        "z": -1,
        "type": "sun"
      },
      {
        "name": "Nimbus",
        "mass": 849,
        "radius": 3.6,
        "color": 0x95d5b2,
        "orbit": {
          "cx": 0,
          "cz": -1,
          "radius": 19,
          "omega": -0.16,
          "phase": 3.94
        }
      },
      {
        "name": "Nova",
        "mass": 640,
        "radius": 3.8,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 0,
          "cz": -1,
          "radius": 35,
          "omega": 0.25,
          "phase": 5.57
        }
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -36,
        "z": 26
      }
    ],
    "name": "Picket Line",
    "hint": "That ship is on patrol. Watch its route before you launch.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": 24,
      "z": 45
    },
    "goal": {
      "x": -30,
      "z": -45,
      "r": 5.4
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Sol",
        "mass": 2351,
        "radius": 6.7,
        "color": 0xffb703,
        "x": 3,
        "z": -6,
        "type": "sun"
      },
      {
        "name": "Onyx",
        "mass": 861,
        "radius": 3.9,
        "color": 0x90e0ef,
        "orbit": {
          "cx": 3,
          "cz": -6,
          "radius": 19,
          "omega": -0.22,
          "phase": 6.06
        }
      },
      {
        "name": "Sage",
        "mass": 1048,
        "radius": 4.8,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": 3,
          "cz": -6,
          "radius": 35,
          "omega": 0.17,
          "phase": 5.69
        }
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -36,
        "z": 22
      }
    ],
    "name": "Gravity Assist",
    "hint": "A heavy star blocks the way. Dive into its well and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": -20,
      "z": 45
    },
    "goal": {
      "x": 2,
      "z": -45,
      "r": 5.1
    },
    "maxLaunch": 46,
    "fuel": 3,
    "bodies": [
      {
        "name": "Helios",
        "mass": 2352,
        "radius": 6.7,
        "color": 0xff9e6b,
        "x": 6,
        "z": 3,
        "type": "sun"
      },
      {
        "name": "Jasper",
        "mass": 1116,
        "radius": 3.9,
        "color": 0xffd166,
        "orbit": {
          "cx": 6,
          "cz": 3,
          "radius": 19,
          "omega": 0.16,
          "phase": 5.53
        }
      },
      {
        "name": "Lumen",
        "mass": 1119,
        "radius": 4.1,
        "color": 0xf4a261,
        "orbit": {
          "cx": 6,
          "cz": 3,
          "radius": 35,
          "omega": 0.24,
          "phase": 1.07
        }
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -35,
        "z": -20
      },
      {
        "radius": 2,
        "x": -37,
        "z": 20
      }
    ],
    "name": "Full Send",
    "hint": "A heavy star blocks the way. Dive into its well and let gravity throw you.",
    "difficulty": 2
  },
  {
    "extent": 62,
    "ship": {
      "x": -27,
      "z": 45
    },
    "goal": {
      "x": -27,
      "z": -45,
      "r": 5.2
    },
    "maxLaunch": 49,
    "fuel": 3,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2406,
        "radius": 6.5,
        "color": 0xffd166,
        "x": 5,
        "z": -7,
        "type": "sun"
      },
      {
        "name": "Coral",
        "mass": 1175,
        "radius": 4.2,
        "color": 0x8ecae6,
        "orbit": {
          "cx": 5,
          "cz": -7,
          "radius": 19,
          "omega": 0.21,
          "phase": 2.45
        }
      },
      {
        "name": "Pebble",
        "mass": 858,
        "radius": 3.9,
        "color": 0x8ecae6,
        "orbit": {
          "cx": 5,
          "cz": -7,
          "radius": 35,
          "omega": 0.18,
          "phase": 0.72
        }
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -37,
        "z": 23
      },
      {
        "radius": 2,
        "x": -36,
        "z": 15
      }
    ],
    "name": "Masterclass",
    "hint": "A heavy star blocks the way. Dive into its well and let gravity throw you.",
    "difficulty": 2
  },
  {
    "name": "Antimatter Ridge",
    "hint": "That antimatter star pushes you AWAY. Ride the pass between push and pull.",
    "extent": 62,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -44,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Nulla",
        "mass": -900,
        "radius": 4.5,
        "color": 0xc77dff,
        "x": -12,
        "z": 0
      },
      {
        "name": "Anchor",
        "mass": 1300,
        "radius": 5,
        "color": 0x90e0ef,
        "x": 16,
        "z": -2
      }
    ],
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": 26,
      "z": 46
    },
    "goal": {
      "x": -23,
      "z": -47,
      "r": 5.3
    },
    "maxLaunch": 47,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 1843,
        "radius": 7.4,
        "color": 0xffb703,
        "x": 4,
        "z": -7,
        "type": "sun"
      },
      {
        "name": "Atlas",
        "mass": 869,
        "radius": 4.2,
        "color": 0x7ae582,
        "orbit": {
          "cx": 4,
          "cz": -7,
          "radius": 19,
          "omega": 0.2,
          "phase": 2.07
        }
      },
      {
        "name": "Onyx",
        "mass": 726,
        "radius": 4.5,
        "color": 0x90e0ef,
        "orbit": {
          "cx": 4,
          "cz": -7,
          "radius": 35,
          "omega": 0.27,
          "phase": 4.96
        }
      },
      {
        "name": "Aversa",
        "mass": -870,
        "radius": 3.6,
        "color": 0xc77dff,
        "x": -47,
        "z": 7
      },
      {
        "name": "Nulla",
        "mass": -718,
        "radius": 3.5,
        "color": 0xc77dff,
        "x": 53,
        "z": 9
      }
    ],
    "name": "The Pass",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": 13,
      "z": 46
    },
    "goal": {
      "x": -27,
      "z": -47,
      "r": 5.1
    },
    "maxLaunch": 46,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 1922,
        "radius": 7.6,
        "color": 0xffd166,
        "x": 11,
        "z": -7,
        "type": "sun"
      },
      {
        "name": "Dune",
        "mass": 1050,
        "radius": 4.3,
        "color": 0x95d5b2,
        "orbit": {
          "cx": 11,
          "cz": -7,
          "radius": 19,
          "omega": -0.13,
          "phase": 1.67
        }
      },
      {
        "name": "Mint",
        "mass": 1180,
        "radius": 4.2,
        "color": 0xf4a261,
        "orbit": {
          "cx": 11,
          "cz": -7,
          "radius": 35,
          "omega": -0.24,
          "phase": 0.12
        }
      },
      {
        "name": "Antara",
        "mass": -822,
        "radius": 4,
        "color": 0xc77dff,
        "x": -37,
        "z": 18
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -33,
        "z": -2
      }
    ],
    "name": "Push and Pull",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": -23,
      "z": 46
    },
    "goal": {
      "x": 8,
      "z": -47,
      "r": 5.2
    },
    "maxLaunch": 46,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Vera",
        "mass": 2142,
        "radius": 8.5,
        "color": 0xff9e6b,
        "x": 3,
        "z": 2,
        "type": "sun"
      },
      {
        "name": "Echo",
        "mass": 631,
        "radius": 3.9,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 3,
          "cz": 2,
          "radius": 19,
          "omega": -0.18,
          "phase": 6.18
        }
      },
      {
        "name": "Dune",
        "mass": 1058,
        "radius": 3.9,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 3,
          "cz": 2,
          "radius": 35,
          "omega": -0.14,
          "phase": 3.76
        }
      },
      {
        "name": "Nulla",
        "mass": -687,
        "radius": 3.8,
        "color": 0xc77dff,
        "x": 50,
        "z": -16
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -36,
        "z": 28
      }
    ],
    "name": "Ridge Runner",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": -2,
      "z": 46
    },
    "goal": {
      "x": -28,
      "z": -47,
      "r": 5.3
    },
    "maxLaunch": 46,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 1952,
        "radius": 7,
        "color": 0xffd166,
        "x": 12,
        "z": -11,
        "type": "sun"
      },
      {
        "name": "Echo",
        "mass": 1070,
        "radius": 5,
        "color": 0xf4a261,
        "orbit": {
          "cx": 12,
          "cz": -11,
          "radius": 19,
          "omega": -0.25,
          "phase": 4.23
        }
      },
      {
        "name": "Koa",
        "mass": 1193,
        "radius": 3.7,
        "color": 0x8ecae6,
        "orbit": {
          "cx": 12,
          "cz": -11,
          "radius": 35,
          "omega": -0.17,
          "phase": 0.16
        }
      },
      {
        "name": "Antara",
        "mass": -500,
        "radius": 4.3,
        "color": 0xc77dff,
        "x": -40,
        "z": -29
      }
    ],
    "waypoints": [
      {
        "x": -37,
        "z": -7,
        "r": 4.5,
        "type": "station"
      }
    ],
    "pickups": [
      {
        "x": -26,
        "z": 14,
        "fuel": 1.5
      },
      {
        "x": -16,
        "z": 31,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.1,
      0.5
    ],
    "fuelRequired": true,
    "name": "Waystation",
    "hint": "Dock at the station 🛰 first — but stops never refuel. Grab fuel cells on the way!",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": 10,
      "z": 46
    },
    "goal": {
      "x": 17,
      "z": -47,
      "r": 5.4
    },
    "maxLaunch": 45,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2384,
        "radius": 8.3,
        "color": 0xff9e6b,
        "x": -5,
        "z": -2,
        "type": "sun"
      },
      {
        "name": "Basil",
        "mass": 937,
        "radius": 4.2,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -5,
          "cz": -2,
          "radius": 19,
          "omega": -0.23,
          "phase": 6.24
        }
      },
      {
        "name": "Jasper",
        "mass": 1135,
        "radius": 4.3,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -5,
          "cz": -2,
          "radius": 35,
          "omega": -0.26,
          "phase": 3.22
        }
      },
      {
        "name": "Antara",
        "mass": -549,
        "radius": 3.6,
        "color": 0xc77dff,
        "x": 45,
        "z": -14
      }
    ],
    "waypoints": [
      {
        "x": 37,
        "z": 15,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 30,
        "z": 29
      }
    ],
    "pickups": [
      {
        "x": 21,
        "z": 35,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.11,
      0.35
    ],
    "fuelRequired": true,
    "name": "Backpressure",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": -21,
      "z": 46
    },
    "goal": {
      "x": -17,
      "z": -47,
      "r": 4.9
    },
    "maxLaunch": 45,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Sol",
        "mass": 2177,
        "radius": 7.4,
        "color": 0xffb703,
        "x": 4,
        "z": -5,
        "type": "sun"
      },
      {
        "name": "Echo",
        "mass": 1082,
        "radius": 4.3,
        "color": 0x8ecae6,
        "orbit": {
          "cx": 4,
          "cz": -5,
          "radius": 19,
          "omega": 0.22,
          "phase": 1.47
        }
      },
      {
        "name": "Halo",
        "mass": 1268,
        "radius": 3.5,
        "color": 0xffd166,
        "orbit": {
          "cx": 4,
          "cz": -5,
          "radius": 35,
          "omega": -0.25,
          "phase": 5.65
        }
      },
      {
        "name": "Umbra",
        "mass": -913,
        "radius": 3.9,
        "color": 0xc77dff,
        "x": 49,
        "z": 18
      }
    ],
    "waypoints": [
      {
        "x": -42,
        "z": -3,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -31,
        "z": -31
      }
    ],
    "pickups": [
      {
        "x": -32,
        "z": 31,
        "fuel": 1.5
      },
      {
        "x": -32,
        "z": 21,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.11,
      0.11
    ],
    "fuelRequired": true,
    "name": "Crosswind",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": -26,
      "z": 46
    },
    "goal": {
      "x": -8,
      "z": -47,
      "r": 4.7
    },
    "maxLaunch": 44,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 2392,
        "radius": 7.9,
        "color": 0xffb703,
        "x": 8,
        "z": 1,
        "type": "sun"
      },
      {
        "name": "Frost",
        "mass": 937,
        "radius": 4.5,
        "color": 0x95d5b2,
        "orbit": {
          "cx": 8,
          "cz": 1,
          "radius": 19,
          "omega": -0.25,
          "phase": 1.34
        }
      },
      {
        "name": "Rhea",
        "mass": 924,
        "radius": 3.8,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 8,
          "cz": 1,
          "radius": 35,
          "omega": -0.3,
          "phase": 2.65
        }
      },
      {
        "name": "Umbra",
        "mass": -989,
        "radius": 3.5,
        "color": 0xc77dff,
        "x": -39,
        "z": -31
      }
    ],
    "waypoints": [
      {
        "x": -41,
        "z": 2,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": -33,
        "z": 19
      }
    ],
    "pickups": [
      {
        "x": -33,
        "z": 30,
        "fuel": 1.5
      },
      {
        "x": -41,
        "z": 22,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.11,
      0.55
    ],
    "fuelRequired": false,
    "name": "The Squeeze",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": 4,
      "z": 46
    },
    "goal": {
      "x": 18,
      "z": -47,
      "r": 4.6
    },
    "maxLaunch": 48,
    "fuel": 1.8,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 2356,
        "radius": 8,
        "color": 0xffb703,
        "x": -10,
        "z": -1,
        "type": "sun"
      },
      {
        "name": "Lyra",
        "mass": 664,
        "radius": 4.9,
        "color": 0xffd166,
        "orbit": {
          "cx": -10,
          "cz": -1,
          "radius": 19,
          "omega": -0.19,
          "phase": 2.99
        }
      },
      {
        "name": "Vesta",
        "mass": 814,
        "radius": 3.9,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -10,
          "cz": -1,
          "radius": 35,
          "omega": -0.24,
          "phase": 2.82
        }
      },
      {
        "name": "Aversa",
        "mass": -798,
        "radius": 3.5,
        "color": 0xc77dff,
        "x": 22,
        "z": 38
      }
    ],
    "waypoints": [
      {
        "x": 36,
        "z": 2,
        "r": 4.5,
        "type": "station"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "x": 32,
        "z": -27
      }
    ],
    "pickups": [
      {
        "x": 25,
        "z": 25,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.65,
      0.1
    ],
    "fuelRequired": true,
    "name": "Turbulence",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "extent": 64,
    "ship": {
      "x": 27,
      "z": 46
    },
    "goal": {
      "x": 29,
      "z": -47,
      "r": 4.7
    },
    "maxLaunch": 46,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Helios",
        "mass": 1939,
        "radius": 6.5,
        "color": 0xffd166,
        "x": -4,
        "z": -3,
        "type": "sun"
      },
      {
        "name": "Pebble",
        "mass": 1008,
        "radius": 4.5,
        "color": 0xbde0fe,
        "orbit": {
          "cx": -4,
          "cz": -3,
          "radius": 19,
          "omega": 0.27,
          "phase": 2.18
        }
      },
      {
        "name": "Frost",
        "mass": 1172,
        "radius": 3.5,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -4,
          "cz": -3,
          "radius": 35,
          "omega": 0.26,
          "phase": 0.64
        }
      },
      {
        "name": "Inverse",
        "mass": -911,
        "radius": 3.6,
        "color": 0xc77dff,
        "x": -49,
        "z": 17
      }
    ],
    "waypoints": [
      {
        "x": 54,
        "z": 4,
        "r": 4.5,
        "type": "station"
      }
    ],
    "pickups": [
      {
        "x": 47,
        "z": 23,
        "fuel": 1.5
      },
      {
        "x": 35,
        "z": 31,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.1,
      0.1
    ],
    "fuelRequired": true,
    "name": "Summit",
    "hint": "Violet antimatter stars push you AWAY. Ride the passes between push and pull.",
    "difficulty": 3
  },
  {
    "name": "Moonshot",
    "hint": "The moon keeps moving — even while you aim. Time your release!",
    "extent": 62,
    "ship": {
      "x": 0,
      "z": 44
    },
    "goal": {
      "x": 0,
      "z": -46,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 3.5,
    "bodies": [
      {
        "name": "Aegis",
        "mass": 2200,
        "radius": 7,
        "color": 0xbde0fe,
        "x": 0,
        "z": -4
      },
      {
        "name": "Luna",
        "mass": 520,
        "radius": 3,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 20,
          "omega": 0.7,
          "phase": 0.8
        }
      }
    ],
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": 28,
      "z": 48
    },
    "goal": {
      "x": -11,
      "z": -48,
      "r": 4.9
    },
    "maxLaunch": 47,
    "fuel": 4,
    "bodies": [
      {
        "name": "Sol",
        "mass": 2238,
        "radius": 6.6,
        "color": 0xffb703,
        "x": 7,
        "z": 0,
        "type": "sun"
      },
      {
        "name": "Pebble",
        "mass": 1177,
        "radius": 4.5,
        "color": 0xf4a261,
        "orbit": {
          "cx": 7,
          "cz": 0,
          "radius": 19,
          "omega": 0.5,
          "phase": 5.41
        }
      },
      {
        "name": "Basil",
        "mass": 631,
        "radius": 3.9,
        "color": 0x95d5b2,
        "orbit": {
          "cx": 7,
          "cz": 0,
          "radius": 35,
          "omega": 0.33,
          "phase": 5.37
        }
      }
    ],
    "name": "Orbit Window",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": 29,
      "z": 48
    },
    "goal": {
      "x": -23,
      "z": -48,
      "r": 5
    },
    "maxLaunch": 47,
    "fuel": 4,
    "bodies": [
      {
        "name": "Kestrel",
        "mass": 2488,
        "radius": 7.3,
        "color": 0xff9e6b,
        "x": 13,
        "z": -7,
        "type": "sun"
      },
      {
        "name": "Rhea",
        "mass": 808,
        "radius": 4.5,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 13,
          "cz": -7,
          "radius": 19,
          "omega": -0.52,
          "phase": 3.6
        }
      },
      {
        "name": "Frost",
        "mass": 1221,
        "radius": 4.2,
        "color": 0xf4a261,
        "orbit": {
          "cx": 13,
          "cz": -7,
          "radius": 35,
          "omega": -0.42,
          "phase": 1.95
        }
      }
    ],
    "name": "Waltz",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": 3,
      "z": 48
    },
    "goal": {
      "x": -22,
      "z": -48,
      "r": 4.9
    },
    "maxLaunch": 45,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Rana",
        "mass": 2904,
        "radius": 8.1,
        "color": 0xffd166,
        "x": 7,
        "z": -8,
        "type": "sun"
      },
      {
        "name": "Quartz",
        "mass": 969,
        "radius": 3.5,
        "color": 0x95d5b2,
        "orbit": {
          "cx": 7,
          "cz": -8,
          "radius": 19.3,
          "omega": 0.43,
          "phase": 2.67
        }
      },
      {
        "name": "Juno",
        "mass": 676,
        "radius": 4.7,
        "color": 0x7ae582,
        "orbit": {
          "cx": 7,
          "cz": -8,
          "radius": 35.3,
          "omega": -0.48,
          "phase": 1.02
        }
      }
    ],
    "waypoints": [
      {
        "x": -33,
        "z": 23,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": -43,
        "z": -20,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -10,
        "z": 40,
        "fuel": 1.5
      },
      {
        "x": -38,
        "z": 12,
        "fuel": 1.5
      },
      {
        "x": -25,
        "z": 36,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.11,
      0.11,
      0.11
    ],
    "fuelRequired": true,
    "name": "First Haul",
    "hint": "Grab the cargo 📦 and haul it to the dropoff 📥 — and fuel cells are NOT optional out here.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": -28,
      "z": 48
    },
    "goal": {
      "x": 16,
      "z": -48,
      "r": 4.9
    },
    "maxLaunch": 46,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 2999,
        "radius": 7,
        "color": 0xffd166,
        "x": 14,
        "z": 3,
        "type": "sun"
      },
      {
        "name": "Juno",
        "mass": 986,
        "radius": 4.5,
        "color": 0xff8fa3,
        "orbit": {
          "cx": 14,
          "cz": 3,
          "radius": 19,
          "omega": -0.32,
          "phase": 0.71
        }
      },
      {
        "name": "Rhea",
        "mass": 1223,
        "radius": 4.2,
        "color": 0x90e0ef,
        "orbit": {
          "cx": 14,
          "cz": 3,
          "radius": 35,
          "omega": -0.43,
          "phase": 6.12
        }
      }
    ],
    "waypoints": [
      {
        "x": -37,
        "z": 7,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": -18,
        "z": -33,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -35,
        "z": 35,
        "fuel": 1.5
      },
      {
        "x": -35,
        "z": -8,
        "fuel": 1.5
      },
      {
        "x": -29,
        "z": -16,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.1,
      0.1,
      0.1
    ],
    "fuelRequired": true,
    "name": "Pendulum",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": 29,
      "z": 48
    },
    "goal": {
      "x": -28,
      "z": -48,
      "r": 4.9
    },
    "maxLaunch": 46,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Vera",
        "mass": 2416,
        "radius": 7.3,
        "color": 0xffd166,
        "x": -15,
        "z": 4,
        "type": "sun"
      },
      {
        "name": "Rhea",
        "mass": 1204,
        "radius": 4.4,
        "color": 0x8ecae6,
        "orbit": {
          "cx": -15,
          "cz": 4,
          "radius": 19,
          "omega": 0.53,
          "phase": 2.93
        }
      },
      {
        "name": "Iris",
        "mass": 1204,
        "radius": 4.1,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -15,
          "cz": 4,
          "radius": 35,
          "omega": -0.49,
          "phase": 3.73
        }
      }
    ],
    "waypoints": [
      {
        "x": 33,
        "z": 9,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": 12,
        "z": -34,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 33,
          "z1": -3,
          "x2": 36,
          "z2": -25,
          "period": 4.3,
          "phase": 0.65
        }
      }
    ],
    "pickups": [
      {
        "x": 34,
        "z": 27,
        "fuel": 1.5
      },
      {
        "x": 30,
        "z": 36,
        "fuel": 1.5
      },
      {
        "x": 25,
        "z": -16,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.1,
      0.1,
      0.2
    ],
    "fuelRequired": true,
    "name": "Metronome",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": 14,
      "z": 48
    },
    "goal": {
      "x": -6,
      "z": -48,
      "r": 4.8
    },
    "maxLaunch": 46,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2397,
        "radius": 7.3,
        "color": 0xff9e6b,
        "x": -14,
        "z": 3,
        "type": "sun"
      },
      {
        "name": "Koa",
        "mass": 953,
        "radius": 4.3,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -14,
          "cz": 3,
          "radius": 19,
          "omega": 0.41,
          "phase": 4.09
        }
      },
      {
        "name": "Juno",
        "mass": 1015,
        "radius": 4,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -14,
          "cz": 3,
          "radius": 35,
          "omega": 0.33,
          "phase": 2.77
        }
      }
    ],
    "waypoints": [
      {
        "x": 32,
        "z": 12,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": 25,
        "z": -32,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 37,
          "z1": 25,
          "x2": 51,
          "z2": 8,
          "period": 6.3,
          "phase": 0.7
        }
      }
    ],
    "pickups": [
      {
        "x": 26,
        "z": 25,
        "fuel": 1.5
      },
      {
        "x": 30,
        "z": -8,
        "fuel": 1.5
      },
      {
        "x": 20,
        "z": 38,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.1,
      0.1,
      0.1
    ],
    "fuelRequired": true,
    "name": "Eclipse",
    "hint": "Gravity assist: launch when a moving body can sling you forward, not against you.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": 20,
      "z": 48
    },
    "goal": {
      "x": -32,
      "z": -48,
      "r": 5.2
    },
    "maxLaunch": 46,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Vera",
        "mass": 2941,
        "radius": 8.1,
        "color": 0xffb703,
        "x": 9,
        "z": -10,
        "type": "sun"
      },
      {
        "name": "Atlas",
        "mass": 609,
        "radius": 3.9,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 9,
          "cz": -10,
          "radius": 19,
          "omega": 0.39,
          "phase": 5.25
        }
      },
      {
        "name": "Quartz",
        "mass": 626,
        "radius": 4.5,
        "color": 0x8ecae6,
        "orbit": {
          "cx": 9,
          "cz": -10,
          "radius": 35,
          "omega": 0.57,
          "phase": 1.23
        }
      }
    ],
    "waypoints": [
      {
        "x": -22,
        "z": 25,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": -43,
        "z": -14,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": 3,
        "z": 42,
        "fuel": 1.5
      },
      {
        "x": -32,
        "z": 11,
        "fuel": 1.5
      },
      {
        "x": -45,
        "z": 3,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.1,
      0.1,
      0.1
    ],
    "fuelRequired": true,
    "name": "Revolution",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": -29,
      "z": 48
    },
    "goal": {
      "x": 21,
      "z": -48,
      "r": 4.9
    },
    "maxLaunch": 44,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Helios",
        "mass": 2970,
        "radius": 7.8,
        "color": 0xff9e6b,
        "x": -17,
        "z": -8,
        "type": "sun"
      },
      {
        "name": "Sage",
        "mass": 1049,
        "radius": 4,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -17,
          "cz": -8,
          "radius": 19,
          "omega": -0.36,
          "phase": 5.31
        }
      },
      {
        "name": "Vesta",
        "mass": 750,
        "radius": 4.8,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -17,
          "cz": -8,
          "radius": 35,
          "omega": -0.41,
          "phase": 0.31
        }
      }
    ],
    "waypoints": [
      {
        "x": 10,
        "z": 30,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": 29,
        "z": -9,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -8,
        "z": 40,
        "fuel": 1.5
      },
      {
        "x": 26,
        "z": 8,
        "fuel": 1.5
      },
      {
        "x": 19,
        "z": 20,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.11,
      0.11,
      0.22
    ],
    "fuelRequired": true,
    "name": "Perfect Timing",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "extent": 66,
    "ship": {
      "x": 5,
      "z": 48
    },
    "goal": {
      "x": 2,
      "z": -48,
      "r": 4.8
    },
    "maxLaunch": 48,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Rana",
        "mass": 2649,
        "radius": 7.4,
        "color": 0xffb703,
        "x": -16,
        "z": -4,
        "type": "sun"
      },
      {
        "name": "Cinder",
        "mass": 839,
        "radius": 3.9,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -16,
          "cz": -4,
          "radius": 19,
          "omega": -0.32,
          "phase": 0.53
        }
      },
      {
        "name": "Frost",
        "mass": 921,
        "radius": 4.3,
        "color": 0x95d5b2,
        "orbit": {
          "cx": -16,
          "cz": -4,
          "radius": 35,
          "omega": -0.43,
          "phase": 5.78
        }
      }
    ],
    "waypoints": [
      {
        "x": 31,
        "z": 5,
        "r": 4.5,
        "type": "cargo"
      },
      {
        "x": 30,
        "z": -27,
        "r": 4.5,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 29,
          "z1": -14,
          "x2": 41,
          "z2": -4,
          "period": 6.3,
          "phase": 0.71
        }
      }
    ],
    "pickups": [
      {
        "x": 13,
        "z": 35,
        "fuel": 1.5
      },
      {
        "x": 20,
        "z": 23,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.1,
      0.1,
      0.19
    ],
    "fuelRequired": true,
    "name": "Clockwork",
    "hint": "Everything is moving — even while you aim. Timing is everything.",
    "difficulty": 4
  },
  {
    "name": "Event Horizon",
    "hint": "Nothing escapes the red ring. Skim close for a huge slingshot — but not TOO close.",
    "extent": 64,
    "ship": {
      "x": -38,
      "z": 44
    },
    "goal": {
      "x": 34,
      "z": -44,
      "r": 4.5
    },
    "maxLaunch": 44,
    "fuel": 4,
    "bodies": [
      {
        "name": "Maw",
        "mass": 5200,
        "radius": 3.5,
        "horizon": 6.5,
        "color": 0x1a1a2e,
        "x": 0,
        "z": 0,
        "type": "blackhole"
      }
    ],
    "difficulty": 5
  },
  {
    "name": "Grand Tour",
    "hint": "Everything at once. Take your time — plot the long way round.",
    "extent": 74,
    "ship": {
      "x": 30,
      "z": 56
    },
    "goal": {
      "x": -34,
      "z": -50,
      "r": 5
    },
    "maxLaunch": 48,
    "fuel": 5,
    "bodies": [
      {
        "name": "Titan",
        "mass": 1700,
        "radius": 6,
        "color": 0xffd166,
        "x": 26,
        "z": 14
      },
      {
        "name": "Wisp",
        "mass": 420,
        "radius": 2.5,
        "color": 0xe2e2e2,
        "orbit": {
          "parent": 0,
          "radius": 15,
          "omega": 0.8,
          "phase": 2.1
        }
      },
      {
        "name": "Umbra",
        "mass": -900,
        "radius": 4.5,
        "color": 0xc77dff,
        "x": 2,
        "z": -4
      },
      {
        "name": "Maw II",
        "mass": 4200,
        "radius": 3,
        "horizon": 5.5,
        "color": 0x1a1a2e,
        "x": -26,
        "z": -18,
        "type": "blackhole"
      }
    ],
    "difficulty": 5
  },
  {
    "extent": 72,
    "ship": {
      "x": -27,
      "z": 52
    },
    "goal": {
      "x": 4,
      "z": -53,
      "r": 4.2
    },
    "maxLaunch": 41,
    "fuel": 5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 3218,
        "radius": 7.6,
        "color": 0xffb703,
        "x": -9,
        "z": -1,
        "type": "sun"
      },
      {
        "name": "Echo",
        "mass": 693,
        "radius": 4.6,
        "color": 0x8ecae6,
        "orbit": {
          "cx": -9,
          "cz": -1,
          "radius": 19.4,
          "omega": -0.3,
          "phase": 3.39
        }
      },
      {
        "name": "Sage",
        "mass": 1017,
        "radius": 4.8,
        "color": 0xbde0fe,
        "orbit": {
          "cx": -9,
          "cz": -1,
          "radius": 35.4,
          "omega": -0.41,
          "phase": 3.75
        }
      },
      {
        "name": "Abyss",
        "mass": 3553,
        "radius": 3,
        "horizon": 6.2,
        "color": 0x1a1a2e,
        "type": "blackhole",
        "x": 42,
        "z": -3
      },
      {
        "name": "Nulla",
        "mass": -537,
        "radius": 3.8,
        "color": 0xc77dff,
        "x": -49,
        "z": -35
      }
    ],
    "name": "Star System",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 76,
    "ship": {
      "x": 28,
      "z": 55
    },
    "goal": {
      "x": -15,
      "z": -55,
      "r": 4.5
    },
    "maxLaunch": 46,
    "fuel": 5,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 3344,
        "radius": 7.8,
        "color": 0xff9e6b,
        "x": 12,
        "z": 4,
        "type": "sun"
      },
      {
        "name": "Frost",
        "mass": 738,
        "radius": 3.7,
        "color": 0x90e0ef,
        "orbit": {
          "cx": 12,
          "cz": 4,
          "radius": 22.4,
          "omega": -0.44,
          "phase": 2.83
        }
      },
      {
        "name": "Iris",
        "mass": 989,
        "radius": 3.6,
        "color": 0xffd166,
        "orbit": {
          "cx": 12,
          "cz": 4,
          "radius": 38.4,
          "omega": -0.22,
          "phase": 1.63
        }
      },
      {
        "name": "Antara",
        "mass": -741,
        "radius": 4.3,
        "color": 0xc77dff,
        "x": -43,
        "z": -16
      }
    ],
    "name": "Dark Passage",
    "hint": "Your engine can't brute-force this one. Wait for a planet to swing by and steal its momentum.",
    "difficulty": 5
  },
  {
    "extent": 71,
    "ship": {
      "x": 17,
      "z": 51
    },
    "goal": {
      "x": 27,
      "z": -52,
      "r": 4.3
    },
    "maxLaunch": 38,
    "fuel": 5,
    "bodies": [
      {
        "name": "Vera",
        "mass": 3697,
        "radius": 7.3,
        "color": 0xffb703,
        "x": -5,
        "z": -9,
        "type": "sun"
      },
      {
        "name": "Lumen",
        "mass": 1047,
        "radius": 4,
        "color": 0x8ecae6,
        "orbit": {
          "cx": -5,
          "cz": -9,
          "radius": 19.5,
          "omega": -0.55,
          "phase": 1.68
        }
      },
      {
        "name": "Coral",
        "mass": 739,
        "radius": 4.7,
        "color": 0x90e0ef,
        "orbit": {
          "cx": -5,
          "cz": -9,
          "radius": 35.5,
          "omega": 0.24,
          "phase": 4.2
        }
      }
    ],
    "name": "Planetfall",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 76,
    "ship": {
      "x": 18,
      "z": 55
    },
    "goal": {
      "x": 22,
      "z": -55,
      "r": 4.4
    },
    "maxLaunch": 45,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2750,
        "radius": 6.6,
        "color": 0xffb703,
        "x": -10,
        "z": -13,
        "type": "sun"
      },
      {
        "name": "Mica",
        "mass": 750,
        "radius": 4.9,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -10,
          "cz": -13,
          "radius": 20.8,
          "omega": -0.31,
          "phase": 6.25
        }
      },
      {
        "name": "Atlas",
        "mass": 944,
        "radius": 4.4,
        "color": 0xffc8dd,
        "orbit": {
          "cx": -10,
          "cz": -13,
          "radius": 36.8,
          "omega": -0.36,
          "phase": 1.83
        }
      }
    ],
    "waypoints": [
      {
        "x": -12,
        "z": 35,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": 37,
        "z": -7,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": 6,
        "z": 45,
        "fuel": 1.5
      },
      {
        "x": 24,
        "z": 22,
        "fuel": 1.5
      },
      {
        "x": 30,
        "z": 10,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.11,
      0.11,
      0.11
    ],
    "fuelRequired": true,
    "name": "The Gauntlet",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 75,
    "ship": {
      "x": -17,
      "z": 54
    },
    "goal": {
      "x": -33,
      "z": -55,
      "r": 4.5
    },
    "maxLaunch": 42,
    "fuel": 1.5,
    "bodies": [
      {
        "name": "Aurum",
        "mass": 2993,
        "radius": 6.9,
        "color": 0xffd166,
        "x": 12,
        "z": 5,
        "type": "sun"
      },
      {
        "name": "Juno",
        "mass": 1037,
        "radius": 3.9,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": 12,
          "cz": 5,
          "radius": 22.3,
          "omega": -0.41,
          "phase": 6.22
        }
      },
      {
        "name": "Mica",
        "mass": 540,
        "radius": 4.1,
        "color": 0xbde0fe,
        "orbit": {
          "cx": 12,
          "cz": 5,
          "radius": 38.3,
          "omega": -0.54,
          "phase": 6
        }
      },
      {
        "name": "Maw",
        "mass": 3849,
        "radius": 3,
        "horizon": 6.2,
        "color": 0x1a1a2e,
        "type": "blackhole",
        "x": 4,
        "z": 59
      }
    ],
    "waypoints": [
      {
        "x": -52,
        "z": 26,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": -48,
        "z": -19,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -38,
        "z": 38,
        "fuel": 1.5
      },
      {
        "x": -55,
        "z": 11,
        "fuel": 1.5
      },
      {
        "x": -28,
        "z": 44,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.4,
      0.12,
      0.12
    ],
    "fuelRequired": true,
    "name": "Singularity",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 75,
    "ship": {
      "x": 29,
      "z": 54
    },
    "goal": {
      "x": 19,
      "z": -55,
      "r": 4.4
    },
    "maxLaunch": 38,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 2693,
        "radius": 8.5,
        "color": 0xffd166,
        "x": -16,
        "z": 0,
        "type": "sun"
      },
      {
        "name": "Coral",
        "mass": 544,
        "radius": 4.8,
        "color": 0xffd166,
        "orbit": {
          "cx": -16,
          "cz": 0,
          "radius": 20.8,
          "omega": -0.43,
          "phase": 0.93
        }
      },
      {
        "name": "Sage",
        "mass": 831,
        "radius": 4.7,
        "color": 0xf4a261,
        "orbit": {
          "cx": -16,
          "cz": 0,
          "radius": 36.8,
          "omega": -0.5,
          "phase": 2.68
        }
      }
    ],
    "waypoints": [
      {
        "x": 46,
        "z": 19,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": 49,
        "z": -19,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "hazards": [
      {
        "radius": 2,
        "patrol": {
          "x1": 29,
          "z1": -15,
          "x2": 40,
          "z2": -33,
          "period": 4.3,
          "phase": 0.25
        }
      }
    ],
    "pickups": [
      {
        "x": 33,
        "z": 42,
        "fuel": 1.5
      },
      {
        "x": 47,
        "z": -3,
        "fuel": 1.5
      },
      {
        "x": 46,
        "z": 8,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.15,
      0.15,
      0.15
    ],
    "fuelRequired": true,
    "name": "Far Shore",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 70,
    "ship": {
      "x": -2,
      "z": 50
    },
    "goal": {
      "x": 4,
      "z": -51,
      "r": 4.2
    },
    "maxLaunch": 39,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Helios",
        "mass": 2831,
        "radius": 8.2,
        "color": 0xffd166,
        "x": 15,
        "z": 2,
        "type": "sun"
      },
      {
        "name": "Nova",
        "mass": 986,
        "radius": 3.8,
        "color": 0xffc8dd,
        "orbit": {
          "cx": 15,
          "cz": 2,
          "radius": 19.1,
          "omega": -0.54,
          "phase": 4.89
        }
      },
      {
        "name": "Vesta",
        "mass": 634,
        "radius": 4,
        "color": 0x8ecae6,
        "orbit": {
          "cx": 15,
          "cz": 2,
          "radius": 35.1,
          "omega": -0.47,
          "phase": 4.18
        }
      }
    ],
    "waypoints": [
      {
        "x": -29,
        "z": 24,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": -26,
        "z": -20,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -14,
        "z": 43,
        "fuel": 1.5
      },
      {
        "x": -35,
        "z": 1,
        "fuel": 1.5
      },
      {
        "x": -24,
        "z": 32,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.14,
      0.14,
      0.14
    ],
    "fuelRequired": true,
    "name": "Last Light",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  },
  {
    "extent": 76,
    "ship": {
      "x": -23,
      "z": 55
    },
    "goal": {
      "x": -14,
      "z": -55,
      "r": 4.5
    },
    "maxLaunch": 44,
    "fuel": 1.4,
    "bodies": [
      {
        "name": "Tsuki",
        "mass": 3096,
        "radius": 6.8,
        "color": 0xff9e6b,
        "x": -13,
        "z": 2,
        "type": "sun"
      },
      {
        "name": "Coral",
        "mass": 938,
        "radius": 3.6,
        "color": 0x7ae582,
        "orbit": {
          "cx": -13,
          "cz": 2,
          "radius": 22.5,
          "omega": -0.38,
          "phase": 1.9
        }
      },
      {
        "name": "Nova",
        "mass": 1086,
        "radius": 4,
        "color": 0xc8b6ff,
        "orbit": {
          "cx": -13,
          "cz": 2,
          "radius": 38.5,
          "omega": -0.28,
          "phase": 2.23
        }
      },
      {
        "name": "Void",
        "mass": 3646,
        "radius": 3,
        "horizon": 6.4,
        "color": 0x1a1a2e,
        "type": "blackhole",
        "x": -54,
        "z": -36
      }
    ],
    "waypoints": [
      {
        "x": -50,
        "z": 35,
        "r": 3.6,
        "type": "cargo"
      },
      {
        "x": -41,
        "z": -39,
        "r": 3.6,
        "type": "dropoff"
      }
    ],
    "pickups": [
      {
        "x": -41,
        "z": 48,
        "fuel": 1.5
      },
      {
        "x": -29,
        "z": 46,
        "fuel": 1.5
      }
    ],
    "legMinCosts": [
      0.11,
      0.11,
      0.37
    ],
    "fuelRequired": true,
    "name": "GravityLoop",
    "hint": "Whole solar systems, weak engines. Ride the planets' orbital momentum — launch windows matter.",
    "difficulty": 5
  }
];
